/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Place;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.util.ArrayList;

/**
 *
 * @author S519459
 */
public class TotalItems
{
    public static  ArrayList<Item> list;

    public ArrayList<Item> getList() {
        return list;
    }

    public void setList(ArrayList<Item> list) {
        this.list = list;
    }
    
public static ArrayList<Item> totalItems()
{
list=new ArrayList<>();

//Badminton
list.add(new Item("Sporting goods/Badminton/BADMINTON GEAR KIT.jpg","Sporting goods","Badminton-1",30.0,0.0,"BADMINTON GEAR KIT","2 Hyper 6000 Series alloy racquets112 Shuttlecocks11Carry bag",null));
list.add(new Item("Sporting goods/Badminton/BADMINTON JUNIOR KIT.jpg","Sporting goods","Badminton-2",40.0,0.0,"BADMINTON JUNIOR KIT","2 AirLite Alloy racquets11 1 Shuttlecocks111 Training shuttlecock11Carry bag11",null));
list.add(new Item("Sporting goods/Badminton/BADMINTON SET.jpg","Sporting goods","Badminton-3",30.0,0.0,"BADMINTON SET","4 Hyper 6000 Series alloy racquets113 shuttlecocks112 telescoping plastic poles11Badminton net11Hooks11Carry bag",null));
list.add(new Item("Sporting goods/Badminton/BADMINTON TOUR SET.jpg","Sporting goods","Badminton-4",30.0,25.0,"BADMINTON TOUR SET","4 Hyper 6000 Series alloy racquets113 Shuttlecocks11Badminton net112 Steel poles11Hooks11Thermal bag11",null));
list.add(new Item("Sporting goods/Badminton/BLAZE 200 BADMINTON RACKET.jpg","Sporting goods","Badminton-5",30.0,50.0,"BLAZE 200 BADMINTON RACKET","Micronized Carbon Fiber11Light Speed11Strung11",null));
 
 //cricket bats
list.add(new Item("Sporting goods/cricketbats/Gray Nicolls Powerbow Blast Cricket Bat.jpg","Sporting goods","cricketbats-1",40.0,0.0,"Gray Nicolls Powerbow Blast Cricket Bat","This Gray Nicolls Powerbow Blast Cricket Bat has been crafted with a long exaggerated bow enhanced by an imposing low blade profile, the perfect combination for any player looking for power. This Gray Nicolls cricket bat has a semi oval handle for comfort and control, whilst the new zone pro grip gives you the confidence to execute a wide range of shots11",null));
list.add(new Item("Sporting goods/cricketbats/Gunn And Moore Six6 F4.5 Original Cricket Bat.jpg","Sporting goods","cricketbats-2",40.0,10.0,"Gunn And Moore Six6 F4.5 Original Cricket Bat","This exquisite Gunn and Moore Six6 F4.5 Original Cricket Bat has been crafted with prime English willow, ensuring long lasting durability whilst the substantial F4.5 contoured edges and powerarc bow helps generate power to make boundaries and the ripple grip means you can play shots with confidence",null));
list.add(new Item("Sporting goods/cricketbats/Kookaburra Kahuna Cobra Cricket Bat.jpg","Sporting goods","cricketbats-3",40.0,0.0,"Kookaburra Kahuna Cobra Cricket Bat","Get the most out of your performance with this Kookaburra Kahuna Cobra Cricket Bat which benefits form having a big sweet spot, allowing you to get more out of shots not played from the centre of the bat, whilst the super spine gives you enhanced power. ThisKookaburra cricket bat has been crafted with power drive technology, reinforcing the bond between handle and the blade which maximises durability and power transfer11",null));
list.add(new Item("Sporting goods/cricketbats/Kookaburra Verve Viper Bat Junior.jpg","Sporting goods","cricketbats-4",40.0,0.0,"Kookaburra Verve Viper Bat Junior","This Junior Kookaburra Verve Viper Bat is extremely lightweight to help get you perfect balance, whilst the super spine allows you to get tremendous power in your shots. This junior cricket bat has a big sweet spot which means that you can get more out of your shots that aren't on the centre of the bat, getting your team those vital runs to be victorious11",null));
list.add(new Item("Sporting goods/cricketbats/Slazenger V1200 Premier Cricket Bat.jpg","Sporting goods","cricketbats-5",40.0,0.0,"Slazenger V1200 Premier Cricket Bat","This Slazenger V1200 Premier Cricket Bat is perfect for an aggressive stroke player due to the premium Kashmir willow construction, providing long lasting durability.11",null));
          
 //golfs
list.add(new Item("Sporting goods/golf/FG TOUR TC GUN BLUE PVD WEDGES.jpg","Sporting goods","golf-1",109.0,18.0,"FG TOUR TC GUN BLUE PVD WEDGES","The Wilson Staff FG Tour TC gun blue PVD wedges feature Traction Control (TC) technology to enhance spin on both long and partial shots.11Aggressive Tour Y grooves are milled for consistency and enhance spin on full swings. Micro-spin enhancers, or sets of 11 laser etched lines between each groove, enhance spin on partial swings.11Tour proven11seek gun blue pvd finish11Traditional sole design11Spin-enhance face technology11Versality11",null));
list.add(new Item("Sporting goods/golf/WILSON STAFF D200 WOMEN'S FAIRWAY WOODS.jpg","Sporting goods","golf-2",120.0,0.0,"WILSON STAFF D200 WOMEN'S FAIRWAY WOODS","The Wilson Staff D200 women’s fairway woods – designed for the female Distance player needing power, accuracy and a confidence-inspiring look at address – features a premium Carpenter Custom 455 maraging steel face insert which maximizes distance from the tee, fairway or rough11Grip:Wilson staff Winn11Shaft options:UST mamiya SL 4511Hand:RH11Player:Adult11",null));
list.add(new Item("Sporting goods/golf/WILSON STAFF FIFTY ELITE PINK GOLF BALLS.jpg","Sporting goods","golf-3",20.0,0.0,"WILSON STAFF FIFTY ELITE PINK GOLF BALLS","WILSON STAFF FIFTY ELITE PINK GOLF BALLS The Wilson Staff Fifty Elite pink golf ball delivers balance to your game. Synergies between an advanced rubber core chemistry and a firm ionomer cover yield a fast, 50 compression golf ball with powerful acceleration11PERFORMANCE BALANCE11The aggressive core is offset by a responsive cover, creating a balance between explosive distance and a soft feel11",null));
list.add(new Item("Sporting goods/golf/WILSON STAFF PRO TOUR DEN CADDY.jpg","Sporting goods","golf-4",80.0,0.0,"WILSON STAFF PRO TOUR DEN CADDY","Whether used on the range as a golf ball container or in the office as a waste bin, the Wilson Staff Pro Tour den caddie provides the perfect gift idea. The steel ring construction, daring red color, and contoured profile contribute to its sporty look11BENEFITS11Contoured profile and bold red color contribute a sleek, sporty look requested by Wilson Staff tour players11Steel ring construction for sturdiness and durability11Two pockets hold and accessories tees on the range",null));
list.add(new Item("Sporting goods/golf/WILSON ULTRA GOLF PACKAGE SET.jpg","Sporting goods","golf-5",200.0,0.0,"WILSON ULTRA GOLF PACKAGE SET","The Wilson Ultra Men’s Package Set is engineered for beginner golfers with improving swing speeds and technique.11SPECIFICATIONS11Men's Standard: 6'2 and under11DRIVER11The lightweight Titanium composite 460cc driver provides explosive distance off the tee11WOOD11Designed with a reinforced graphite shaft and all-weather grip, the easy-to-align fairway wood provides stability on off-center hits11HYBRID11The confidence-inspiring hybrid features a large sweet spot for maximum forgiveness11IRONS11The easy-to-launch iron head design features low weighting technology for optimized ball flight11PUTTER11The weight-balanced head design and alignment grip on the putter improves consistency for a better putting stroke11CARRY BAG11The lightweight, durable carry bag features ergonomic straps, functional pocket space and a self-activating stand11",null));

// list.add(new Item("images/slide2.JPG","Sports","basketball-2",30.0,3.5,"Spalding NBA Neverflat Indoor/Outdoor Basketball","Holds air 10 times longer than traditional basketballs-Provides consistent NBA Game Ball bounce height for at least one year-Redesigned valve with cap eliminates leaks and keeps dirt out-Advanced membrane and NitroFlate air technology virtually eliminates air&aps;s ability to escape-Made from high-performance composite leather, for soft, grippy feel",null));
// list.add(new Item("images/slide1.jpg","Sports","basketball-1",50.0,10.0,"Spalding NBA Zi/O Excel Basketball" ,"Indoor/outdoor composite leather basketball-Deep channel design for better dribble control-Foam backing under the full-ball pebbling for precise ball handling-Official NBA size and weight-Intermediate play size 28.5 inches",null));
// list.add(new Item("images/basketball.jpg","Sports","basketball-3",70.0,10.0,"Wilson Evolution Indoor Game Basketball Official" ,"Composite-Imported-Cushion Core Technology features low-density sponge and butyl rubber-High-definition pebble surface improves grip, feel, and performance-3-ply nylon thread winding; air tight butyl rubber valve-Thermal-molded rubber bladder",null));
// list.add(new Item("images/slide3.jpg","Sports","basketball-4",50.0,10.0,"Franklin Sports Night Lightning Basketball" ,"Extremely bright, glow in the dark rubber-Official size and weight, Pro width channels improve feel and performance-Rubber cover provides superior grip and ball handling-Polyester winding provides superior shape retention and bounce, long lasting air retention bladder-Official B7 size is 29.5\" circumference, Recommended age 13+/High school, college and pro",null));
// 
 //           Electronic goods //      
        
 //cameras
 list.add(new Item("Electronic goods/cameras/Canon PowerShot SX400 16MP Semi SLR.jpg","Electronic goods","cameras-1",250.0,0.0,"Canon PowerShot SX400 16MP Semi SLR","DIGIC 4+ Image Processor?Eco Mode Saves Battery?3.0 inches LCD Display?30x Optical Zoom?White Balancing?Movie Button?Creative Filters Effect?Continuous Shooting Mode?ISO Sensitivity?",null));
 list.add(new Item("Electronic goods/cameras/Nikon Coolpix L29 16.1MP Digital Camera (Silver).jpg","Electronic goods","cameras-2",200.0,45.0,"Nikon Coolpix L29 16.1MP Digital,2.7 inch TFT LCD Screen, Camera (Silver)","2 Year Nikon India Warranty?16.1 Megapixel?5X Optical Zoom?CCD Image Sensor?4X Digital Zoom?Nikkor Lens?Autofocus (AF) : Contrast-detect AF?SUPC: SDL386656105?",null));
 list.add(new Item("Electronic goods/cameras/Sony Cybershot W800 20.1MP (Silver) Combo with Sony NP-BN1.jpg","Electronic goods","cameras-3",240.0,0.0,"Sony Cybershot W800 20.1MP (Silver) Combo with Sony NP-BN1 Rechargeable Battery","Blur Free Clear Images with 20.1 MP Camera?5X Optical Zoom with Sony Lens?5cm Macro Focus Distance?360 Degree Panorama Sweep?Clear Shots under Low Light via Party Mode?Smile Shutter Technology?Easy Editing with In-Built Effects?Easy Storage and Transfer?Charge on the Go with USB?",null));
 list.add(new Item("Electronic goods/cameras/Sony Cybershot W830 20.1MP Digital Camera.jpg","Electronic goods","cameras-4",180.0,0.0,"Sony Cybershot W830 20.1MP Digital Camera","2 Year Sony India Warranty?20.1 Megapixel?2.7 inch LCD Screen?ISO 1600 - 6400 Sensitivity?CCD Image Sensor?HD Recording?Carl Zeiss Lens?f/3.3 - f/8.0 Aperture?HAD CCD Sensor?Sweep Panoroma Feature?SUPC: SDL275938723?",null));
 list.add(new Item("Electronic goods/cameras/Sony Cybershot WX80 16.2MP Digital Camera.jpg","Electronic goods","cameras-5",200.0,10.0,"Sony Cybershot WX80 16.2MP Digital Camera","Exmor® R CMOS Image Sensor?8x Optical Zoom?Built-In Wi-Fi?Full HD Recording?2.7 inches TFT LCD Screen?Intelligent Sweep Panorama?",null));
//cellphones
 list.add(new Item("Electronic goods/cellphones/Apple® - iPhone 6 16GB - Space Gray (Verizon Wireless).jpg","Electronic goods","cellphones-1",600.0,0.0,"Apple® - iPhone 6 16GB - Space Gray (Verizon Wireless)","4.7-inch (diagonal) Retina HD display with 1334-by-750 resolution?A8 chip with M8 motion coprocessor?8MP iSight camera with Focus Pixels and True Tone flash?1080p HD video recording at 60 fps and slo-mo video recording at 240 fps?FaceTime HD camera?Touch ID fingerprint sensor?LTE¹ and 802.11ac Wi-Fi?iOS 8 and iCloud",null));
 list.add(new Item("Electronic goods/cellphones/HTC - One (M8) 4G LTE Cell Phone with 32GB Memory - Gunmetal (Sprint).jpg","Electronic goods","cellphones-2",300.0,49.0,"HTC - One (M8) 4G LTE Cell Phone with 32GB Memory - Gunmetal (Sprint)","Qualcomm Snapdragon 801 processor?Android 4.4 KitKat OS?4G LTE speed?HTC Duo Camera with UltraPixels?HTC BoomSound with dual front-facing stereo speakers and built-in amplifiers deliver sound with less distortion?",null));
 list.add(new Item("Electronic goods/cellphones/LG - G3 Cell Phone - Shine Gold (Sprint).jpg","Electronic goods","cellphones-3",400.0,.0,"LG - G3 Cell Phone - Shine Gold (Sprint)","Qualcomm Snapdragon 801 processor?Android 4.4 KitKat OS?4G LTE speed?5.5 Quad HD touch-screen display?13MP rear-facing camera with laser auto focus and OIS?32GB internal memory plus microSDHC slot?LG Health tracking?Unlock your phone quickly and securely?Access to Google Play?",null));
 list.add(new Item("Electronic goods/cellphones/Motorola - DROID Turbo 4G LTE with 32GB Memory Cell Phone - Blue (Verizon Wireless).jpg","Electronic goods","cellphones-4",350.0,.0,"Motorola - DROID Turbo 4G LTE with 32GB Memory Cell Phone - Blue (Verizon Wireless)","Qualcomm Snapdragon 805 processor?Android 4.4 KitKat OS?4G LTE speed?5.2\" Super AMOLED HD touch screen?21.0MP rear-facing camera with HD recording?32GB internal memory?Use your smartphone as a mobile hotspot?Listen to your favorite tunes?",null));
 list.add(new Item("Electronic goods/cellphones/Samsung - Galaxy S6 4G with 32GB Memory Cell Phone - Black Sapphire.jpg","Electronic goods","cellphones-5",500.0,.0,"Samsung - Galaxy S6 4G with 32GB Memory Cell Phone - Black Sapphire","Samsung Exynos Octa-Core processor?Android 5.0 Lollipop operating system?4G LTE speed?Bluetooth enabled?Dual-band 2.4GHz/5.0GHz Wi-Fi network (802.11a/b/g/n/ac)?5.1\" Super AMOLED touch screen?32GB internal memory?16.0MP rear-facing and 5.0MP front-facing cameras?",null));
 //computers
 list.add(new Item("Electronic goods/computers/ASUS Intel Core i3 4150T (3.0GHz) 4GB DDR3 500GB HDD 20 All-in-One PC.jpg","Electronic goods","computers-1",2500.0,0.0,"ASUS Intel Core i3 4150T (3.0GHz) 4GB DDR3 500GB HDD 20\" All-in-One PCWindows 7 Professional 64-Bit A4310-B1","Intel Core i3 4150T (3.0GHz)?4GB DDR3 500GB HDD?20\" 1600 x 900?Windows 7 Professional 64-Bit?Intel HD Graphics 4400?",null));
 list.add(new Item("Electronic goods/computers/Acer Aspire Intel Core i3 3227U (1.90GHz) 4GB DDR3 1TB HDD 23 All-in-One PC.jpg","Electronic goods","computers-2",3000.0,65.0,"Acer Aspire Intel Core i3 3227U (1.90GHz) 4GB DDR3 1TB HDD 23\" All-in-One PC Windows 8.1 64-Bit AZ3-605-UR2A","Intel Core i3 3227U (1.90GHz)?4GB DDR3 1TB HDD?23\" 1920 x 1080?Windows 8.1 64-Bit?Intel HD Graphics 4000?",null));
 list.add(new Item("Electronic goods/computers/DELL Inspiron Intel Core i3 4150 (3.50GHz) 8GB DDR3 1TB HDD 23 Touchscreen All-in-One PC.jpg","Electronic goods","computers-3",3500.0,0.0,"DELL Inspiron Intel Core i3 4150 (3.50GHz) 8GB DDR3 1TB HDD 23\" Touchscreen All-in-One PC Windows 8.1 64-Bit 5348 (i5348-4446BLK)","High def view?Stunning edge-to-edge touch?Faster everything?Easy connections?",null));
list.add(new Item("Electronic goods/computers/LG Chromebase 2GB DDR3L 16GB SSD (Sandisk) HDD 21.5 All-in-One Google Chrome OS 22CV241-W.jpg","Electronic goods","computers-4",3500.0,0.0,"LG Chromebase 2GB DDR3L 16GB SSD (Sandisk) HDD 21.5\" All-in-One Google Chrome OS 22CV241-W","Intel Celeron processor?2GB DDR3L 1333?16GB SSD (Sandisk)?21.5\" 1920 x 1080 IPS?Google Chrome OS?1.3 MP Webcam?",null));
list.add(new Item("Electronic goods/computers/Lenovo C260 Touch Pentium J2900 (2.41GHz) 4GB DDR3 500GB HDD 19.5 Touchscreen All-in-One PC.jpg","Electronic goods","computers-5",2500.0,0.0,"Lenovo C260 Touch Pentium J2900 (2.41GHz) 4GB DDR3 500GB HDD 19.5\" Touchscreen All-in-One PC Windows 8.1 64-bit 57327041","19.5” HD+ display (1600 x 900)?10-point capacitive touch technology?Space-saving all-in-one design?Front facing stereo speakers?Integrated DVD RW?USB AccuType keyboard?720p HD webcam?Lenovo Rescue System - a simple and quick way to backup and restore your data?",null));
//t
list.add(new Item("Electronic goods/Tv/LG 47LB6500 119.38 cm (47) 3D Full HD Smart LED Television.jpg","Electronic goods","tv-1",800.0,0.0,"LG 47LB6500 119.38 cm (47) 3D Full HD Smart LED Television","Model:LG 47LB6500?Display Size:119.38 cm (47)?Display feature:3D Full HD?Screen Resolution:1920 x 1080p?In the box:Main Unit, 4 Basic 3D Glasses, Magic Remote Built-In, Conventional Remote (Optional)?Aspect Ratio:8 modes (16:9, Just scan, Original, Full Wide, 4:3, 14:9, Zoom,Cinema Zoom)?Dynamic Ratio:500000?Refresh Rate:200HZ?",null));
list.add(new Item("Electronic goods/Tv/Micromax 24B600HD 60 cm (24) HD Ready LED Television.jpg","Electronic goods","tv-2",700.0,15.0,"Micromax 24B600HD 60 cm (24) HD Ready LED Television","Model:24B600HD?Screen Type:LED?Display Size:60 cm (24)?Display Feature:HD Ready; TFT Display?Screen Resolution:1366 x 768?Aspect Ratio:16:09?Additional:Brightness: 250 cd/m2; Contrast Ratio: 3000000:1; Analog TV Reception: M/N, PAL/SECAM/NTSC, B/G, I, D/K, NTSC/PAL; Backlight Module: Edge LED; Color Control; Zoom; 8.5ms Response Time?",null));
list.add(new Item("Electronic goods/Tv/Samsung 23H4003 58 cm (23) HD Ready LED Television.jpg","Electronic goods","tv-3",650.0,0.0,"Samsung 23H4003 58 cm (23) HD Ready LED Television","Model:23H4003?Screen Resolution:1366 x 768 Pixels?Dynamic Ratio:Mega Contrast?Refresh Rate:100 Hz Clear Motion Rate?",null));
list.add(new Item("Electronic goods/Tv/Sony BRAVIA 48W600B 121 cm (48) Full HD Smart LED Television.jpg","Electronic goods","tv-4",550.0,0.0,"Sony BRAVIA 48W600B 121 cm (48) Full HD Smart LED Television","Experience Stunning Picture Details With C-Reality PRO?Full HD Video Quality For Ultimate Entertainment?Crystal Clear Audio Quality?One-Flick Entertainment For All Your Demands?Enjoy Wide Range Of Content With Internet TV?Built-in Wireless LAN For Greater Connectivity and Entertainment?Supersize Your Mobile Content Screen Mirroring?",null));
list.add(new Item("Electronic goods/Tv/Sony BRAVIA KLV-22P402B 54.7 cm (22) Full HD LED Television.jpg","Electronics goods","tv-5",850.0,15.0,"Sony BRAVIA KLV-22P402B 54.7 cm (22) Full HD LED Television","Model:KLV 22P402B-Display Size:Display Size-55.88 cm (22)-Screen Resolution:1920 x 1080-Aspect Ratio:TV: Auto Wide/ Full/ Normal/ Wide Zoom/ Zoom/ PC HDMI: Full 1/ Full 2/ Normal/ 4:3 Default-View Angle:Horizontal: 85 Degree, Vertical: 80 Degree-Headphone Out:1 (Rear/Hybrid with Audio Out)",null));
//Home theater
list.add(new Item("Electronic goods/Home theater/RCA RT2781H 5.1 Home Theater System - 1000 W RMS.jpg","Electronic goods","home theater-1",500.0,0.0,"RCA RT2781H 5.1 Home Theater System - 1000 W RMS","1,000W MAX POWER115.1 CHANNEL113 HDMI INPUTS & 1 HDMI OUTPUT1111OPTICAL & COAXIAL DIGITAL AUDIO INPUTS11RCA INPUT112 RCA INPUTS11AUX INPUT11DOLBY(R) AM/FM TUNER WITH STATION MEMORY PRESETS11",null));
list.add(new Item("Electronic goods/Home theater/RCA RT2911 1,000-Watt Home Theater System.jpg","Electronic goods","home theater-2",400.0,30.0,"RCA RT2911 1,000-Watt Home Theater System","1,000W power11145W x 4 & 210W x 211Full HDMI(R) switching allows users to play HDMI(R) audio from selected HDMI(R) input, while also passing through the HDMI(R) signal to TV113 HDMI(R) inputs, 1 HDMI(R) output11 Digital optical & coaxial audio inputs11 3 aux audio inputs11 Aux input for iPod(R) & other portable audio products11 6.5mm headphone output11Small speaker size11 Digital AM/FM tuner with 30 AM/30 FM station presets",null));
list.add(new Item("Electronic goods/Home theater/Samsung HT-H6500WM Home Theater System.jpg","Electronic goods","home theater-3",550.0,0.0,"Samsung HT-H6500WM Home Theater System","Smart hub11Full webbrowser1111Builtin wifi11Wireless rear speaker11Bluetooth11Crystal amp-plus113D blu-ray11surround sound11Dolby digital plus11Dolby true HD",null));
 list.add(new Item("Electronic goods/Home theater/YAMAHA YHT-399UBL 5.1-Channel Home Theater in a Box.jpg","Electronic goods","home theater-4",450.0,0.0,"YAMAHA YHT-399UBL 5.1-Channel Home Theater in a Box","Five-channel powerful surround sound (100W per channel)11HD Audio format decoding: Dolby® TrueHD and DTS-HD Master Audio11Dolby Digital Plus and DTS-HD High Resolution Audio11Discrete amplifier technology11192kHz / 24-bit Burr-Brown DACs for all channels11High dynamic power, low-impedance drive capability11Two-way speaker drivers for high power input capacity118in. 100W active subwoofer",null));
 list.add(new Item("Electronic goods/Home theater/YAMAHA YHT-4910U AV Home Theater System.jpg","Electronic goods","home theater-5",350.0,0.0,"YAMAHA YHT-4910U AV Home Theater System","5-Channel powerful surround sound11100W per channel (8 Ohms, 1kHz, 0.9% THD, 1-ch driven)1170W per channel (8 Ohms, 20Hz - 20kHz, 0.09% THD, 2-Ch. driven)11Discrete amp configuration11HDMI® (4 in / 1 out) with 4K Ultra HD pass-through for super high resolution images11Front panel USB digital connection for iPod® and iPhone®11Virtual CINEMA FRONT provides virtual surround sound with five speakers in front11Extra Bass enriches powerful bass sound even with small speakers11YPAO™ sound optimization for automatic speaker set up11Multilingual color OSD for improved visibility (English, German, French, Spanish, Russian, Italian, Japanese and Chinese)11ECO mode operation for about 20 percentage less power consumption11",null));
 
 //                 Fashion              //
 //skirts
 list.add(new Item("Fashion/Skirts/Apricot Elastic Waist Multilayers Mesh Skirt.jpg","Fashion","Skirts-1",50.0,0.0,"Apricot Elastic Waist Multilayers Mesh Skirt","Length(cm) :75cm11Waist Size(cm) :62-88cm11Size Available :one-size11Pattern Type :Plain11Silhouette :Pleated11Dresses Length :Knee Length11Color :Apricot11Material :Tulle11Style :Street11",null));
 list.add(new Item("Fashion/Skirts/Black Elastic Waist Polka Dot Pleated Skirt.jpg","Fashion","Skirts-2",40.0,65.0,"Black Elastic Waist Polka Dot Pleated Skirt","Size Available :One Size11Length(cm) :70cm11Pattern Type :Polka Dot11Silhouette :Pleated11Dresses Length :Knee Length11Color :Black11Material :Chiffon11Style :Street11",null));
 list.add(new Item("Fashion/Skirts/Multicolor High Waist Floral Skirt.jpg","Fashion","Skirts-3",60.0,0.0,"Multicolor High Waist Floral Skirt","Size Available :S,M,L11Length(cm) :S:60cm,M:61cm,L:62cm11Waist Size(cm) :S:72cm,M:76cm,L:80cm11Pattern Type :Floral11Silhouette :A Line11Dresses Length :Knee Length11Color :Multi11Material :Cotton Blends11Style :Street11",null));
 list.add(new Item("Fashion/Skirts/Navy Floral Birds Print Pleated Skirt.jpg","Fashion","Skirts-4",40.0,0.0,"Navy Floral Birds Print Pleated Skirt","Size Available :One Size11Length(cm) :88cm11Waist Size(cm) :64-104cm11Pattern Type :Print11Silhouette :Pleated11Dresses Length :Long/Full Length11Color :Navy11Material :Chiffon11Style :Street11",null));
 list.add(new Item("Fashion/Skirts/Red Vintage Floral Mesh Skirt.jpg","Fashion","Skirts-5",30.0,0.0,"Red Vintage Floral Mesh Skirt","Length(cm) :XS:58cm,S:59cm,M:60cm,L:61cm,XL:62cm,XXL:63cm11Waist Size(cm) :XS:60cm,S:64cm,M:68cm,L:72cm,XL:76cm,XXL:80cm11Pattern Type :Floral11Silhouette :Pleated11Dresses Length :Knee Length11Color :Red11Material :Polyester11Style :Fashion11",null));
 
 //Sweaters
 list.add(new Item("Fashion/Sweaters/Black Long Sleeve Diamond Cardigan Sweater.jpg","Fashion","Sweaters-1",55.0,0.0,"Black Long Sleeve Diamond Cardigan Sweater","Size Available :one-size11Sleeve Length(cm) :59cm11Length(cm) :73cm11Bust(cm) :96cm11Season :Fall11Pattern Type :Geometric11Items :Cardigan11Color :Black11Types :Loose11Sleeve Length :Long Sleeve11Material :Acrylic11Styles :Casual11",null));
  list.add(new Item("Fashion/Sweaters/Black Long Sleeve Dipped Hem Knit Sweater.jpg","Fashion","Sweaters-2",50.0,0.0,"Black Long Sleeve Dipped Hem Knit Sweater","Size Available :one-size11Sleeve Length(cm) :67cm11Length(cm) :51/57cm11Bust(cm) :114cm11Season :Fall11Pattern Type :Plain11Items :Pullovers11Color :Black11Types :Loose11Sleeve Length :Long Sleeve11Neckline :Round Neck11Material :Knit11Styles :Casual11",null));
  list.add(new Item("Fashion/Sweaters/Khaki Long Sleeve Faux Fur Lapel Cardigan Sweater.jpg","Fashion","Sweaters-3",35.0,0.0,"Khaki Long Sleeve Faux Fur Lapel Cardigan Sweater","Length(cm) :78cm11Bust(cm) :92cm11Size Available :one-size11Sleeve Length(cm) :60cm11Season :Fall11Pattern Type :Plain11Items :Cardigan11Color :Khaki11Types :Loose11Sleeve Length :Long Sleeve11Neckline :Lapel11Material :Acrylic11",null));
  list.add(new Item("Fashion/Sweaters/Red Lapel Long Sleeve Ouch Cardigan Sweater.jpg","Fashion","Sweaters-4",40.0,0.0,"Red Lapel Long Sleeve Ouch Cardigan Sweater","Bust(cm) :98cm11Shoulder(cm) :54cm11Size Available :one-size11Sleeve Length(cm) :48cm11Length(cm) :58cm11Season :Fall11Pattern Type :Plain11Items :Coat11Color :Red11Types :Loose11Sleeve Length :Long Sleeve11Neckline :Turtleneck11Material :Cotton Blends11Styles :Casual11",null));
  list.add(new Item("Fashion/Sweaters/White Long Sleeve Striped Knit Sweater.jpg","Fashion","Sweaters-5",30.0,40.0,"White Long Sleeve Striped Knit Sweater","Shoulder(cm) :36cm11Size Available :One Size11Sleeve Length(cm) :55cm11Length(cm) :57cm11Bust(cm) :92cm11Season :Fall11Pattern Type :Striped11Items :Pullovers11Color :White11Types :Loose11Sleeve Length :Long Sleeve11Neckline :Round Neck11Material :Cotton Blends11Styles :Casual11",null));
  
  //dresses
  list.add(new Item("Fashion/dresses/CREPE STRAP DETAIL ASYMMETRIC DRESS BLACK.jpg","Fashion","dresses-1",30.0,0.0,"CREPE STRAP DETAIL ASYMMETRIC DRESS BLACK","Give your Little Black Dress collection an update with this chic black crepe dress. With luxe strap detail this textured bodycon beauty with asymmetric hem will give you a standout look this season. Team with nude strappy heels and matching clutch for a touch of evening class11Approx length 102cm/40” (Based on a UK size 8 sample)1195% Polyester 5% Elastane11Cindy wears a UK size 8/ EU size 36/ US size 4 and her height is 5'911",null));
  list.add(new Item("Fashion/dresses/JEANETTE HIGH NECK SWING DRESS GREY.jpg","Fashion","dresses-2",35,0.0,"JEANETTE HIGH NECK SWING DRESS GREY","Swing into style this season with this chic grey knitted swing dress. With luscious long sleeves, super soft fabric and a fierce high neck this dress is a beaut. Team with statement ankle boots and a checked shirt tied around the waist for mega Off Duty vibes11Approx length 89cm/35\" (Based on a UK size 8 sample)1195% Polyester 5% Elastane11Emily wears a UK size 8 and her height is 5'1111",null));
  list.add(new Item("Fashion/dresses/POM POM TRIM BELL SLEEVE SWING DRESS BLACK.jpg","Fashion","dresses-3",25.0,0.0,"POM POM TRIM BELL SLEEVE SWING DRESS BLACK","Work that black jersey swing dress this season. With fierce flared long sleeves and totally dreamy pom-pom trim this dress is a must-have addition to your wardrobe. Team with ankle boots and heaping’s of jewellery for a luscious finish.11Approx length 84cm/33” (Based on a UK size 8 sample)1195% Polyester 5% Elastane11Joanna wears a UK size 8 / EU size 36 / US size 4 and her height is 5'711",null));
  list.add(new Item("Fashion/dresses/SLINKY MAXI DRESS NUDE.jpg","Fashion","dresses-4",30.0,0.0,"SLINKY MAXI DRESS NUDE","We are lusting over slinky fabrics this season and this nude maxi dress is a total dream. With high strappy neckline this nude beauty infused with metallic will give you a seriously standout figure. Team with matching nude strappy heels and box clutch for evening luxe.11Approx length 145cm/57\" (Based on a UK size 8 sample)1195% Polyester 5% Elastane11Cindy wears a UK size 8 / EU size 36 / US size 4 and her height is 5'911",null));
  list.add(new Item("Fashion/dresses/STRIPE DUNGAREE ROMPER CREAM.jpg","Fashion","dresses-5",30.0,0.0,"STRIPE DUNGAREE ROMPER CREAM","Refresh your wardrobe for a hit of minimalist styling. This stripe dungaree romper is a new season winner - effortless, clean and fresh comes to mind. Featuring adjustable straps, button details and turn up design so you can pull of the Style Edit trend in an instant with this beauty. Team with a black crop top, flatforms and a cool hat to work the look.11Approx length 73cm/29” (Based on a UK size 8 sample)11100% Polyester\n11Emily wears a UK size 8/ EU 36/ US 6 and her height is 5'111",null));
  
//tennis
 list.add(new Item("Sporting goods/tennis/BURN 100S TENNIS RACKET.jpg","Sporting goods","tennis-1",199.0,0.0,"BURN 100S TENNIS RACKET","The Burn 100S is the ultimate in booming power for baseliners looking to burn through the competition.  This racket’s aggressive power and 18x16 Spin Effect Technology string pattern allows players to hit heavier shots, deliver precision spin, and create sharper angles",null));
 list.add(new Item("Sporting goods/tennis/BURN 100ULS.jpg","Sporting goods","tennis-2",199.0,0.0,"BURN 100ULS","The Burn 100ULS is the lightest Spin Effect Technology racket.  The Ultra Lite weight is effortless to swing with easy-to-play performance and power.  An 18x16 Spin Effect Technology string pattern provides precision spin.",null));
 list.add(new Item("Sporting goods/tennis/PRO STAFF 97.jpg","Sporting goods","tennis-3",199.0,0.0,"PRO STAFF 97","Roger Federer’s racket with a new modernly classic red and black look, but just a touch lighter. The reduced weight makes for easy swings and control of the ball for the player who likes to attack inside the baseline and finish points at the net with precision volleys. Yet another reason to respect the next generation Pro Staff.11",null));
 list.add(new Item("Sporting goods/tennis/STEAM 105S.jpg","Sporting goods","tennis-4",160.0,80.0,"STEAM 105S","The \"modern game\" is all about spin and Wilson understands spin like no other brand.  Steam rackets are engineered for hard-hitting players who use spin to curve the ball's flight and control the game.  Our revolutionary Spin Effect Technology is the first racket system that actually INCREASES the RPM of every shot by maximizing spin-enhancing string \"snapback\" during ball contact11",null));
 list.add(new Item("Sporting goods/tennis/STEAM 99LS.jpg","Sporting goods","tennis-5",159.0,0.0,"STEAM 99LS","Young players seeking extra spin from a maneuverable frame will love the Steam 99LS.  It is the same responsive Steam frame but extremely light.  With the Spin Effect Technology and extremely lightweight frame, this will give you the perfect blend of power, control, spin, and feel11",null));
 
 //basketball
 list.add(new Item("Sporting goods/basketball/Franklin Sports Night Lightning Basketball.jpg","Sporting goods","basketball-1",21.0,5.0,"Franklin Sports Night Lightning Basketball","Extremely bright, glow in the dark rubber11Official size and weight, Pro width channels improve feel and performance11Rubber cover provides superior grip and ball handling11Polyester winding provides superior shape retention and bounce, long lasting air retention bladder11Official B7 size is 29.5 circumference, Recommended age 13+/High school, college and pro11",null));
 list.add(new Item("Sporting goods/basketball/MacGregor.jpg","Sporting goods","basketball-2",45.0,0.0,"MacGregor","Durable rubber construction11Deep channels and enhanced pebbling for better performance11Recreational Play11Indoor/Outdoor use",null));
 list.add(new Item("Sporting goods/basketball/Spalding NBA Street Basketball - Pink & Purple.jpg","Sporting goods","basketball-3",20.0,0.0,"Spalding NBA Street Basketball - Pink and Purple","New Pink and Purple NBA Street Basketball, Size 6 (28.5\")11Performance Outdoor Cover11Wide Channel Design for Incredible Grip & Feel11Designed for Competitive Street Play11Note: Balls can deflate over time",null));
  list.add(new Item("Sporting goods/basketball/Spalding NBA Zi-O.jpg","Sporting goods","basketball-4",40.0,0.0,"Spalding NBA Zi-O","Indoor/outdoor composite leather basketball11Deep channel design for better dribble control11Foam backing under the full-ball pebbling for precise ball handling11Official NBA size and weight11Intermediate play size 28.5 inches",null));
  list.add(new Item("Sporting goods/basketball/Spalding NBA never flat.jpg","Sportinh goods","basketball-5",50.0,0.0,"Spalding NBA never flat","Holds air 10 times longer than traditional basketballs11Provides consistent NBA Game Ball bounce height for at least one year11Redesigned valve with cap eliminates leaks and keeps dirt out11Advanced membrane and NitroFlate air technology virtually eliminates air's ability to escape11Made from high-performance composite leather, for soft, grippy feel",null));
 
//           Electronic goods //      
        
 //cameras
 list.add(new Item("Electronic goods/cameras/Canon PowerShot SX400 16MP Semi SLR.jpg","Electronic goods","cameras-1",250.0,0.0,"Canon PowerShot SX400 16MP Semi SLR","DIGIC 4+ Image Processor?Eco Mode Saves Battery?3.0 inches LCD Display?30x Optical Zoom?White Balancing?Movie Button?Creative Filters Effect?Continuous Shooting Mode?ISO Sensitivity?",null));
 list.add(new Item("Electronic goods/cameras/Nikon Coolpix L29 16.1MP Digital Camera (Silver).jpg","Electronic goods","cameras-2",200.0,15.0,"Nikon Coolpix L29 16.1MP Digital,2.7 inch TFT LCD Screen, Camera (Silver)","2 Year Nikon India Warranty?16.1 Megapixel?5X Optical Zoom?CCD Image Sensor?4X Digital Zoom?Nikkor Lens?Autofocus (AF) : Contrast-detect AF?SUPC: SDL386656105?",null));
 list.add(new Item("Electronic goods/cameras/Sony Cybershot W800 20.1MP (Silver) Combo with Sony NP-BN1.jpg","Electronic goods","cameras-3",240.0,0.0,"Sony Cybershot W800 20.1MP (Silver) Combo with Sony NP-BN1 Rechargeable Battery","Blur Free Clear Images with 20.1 MP Camera?5X Optical Zoom with Sony Lens?5cm Macro Focus Distance?360 Degree Panorama Sweep?Clear Shots under Low Light via Party Mode?Smile Shutter Technology?Easy Editing with In-Built Effects?Easy Storage and Transfer?Charge on the Go with USB?",null));
 list.add(new Item("Electronic goods/cameras/Sony Cybershot W830 20.1MP Digital Camera.jpg","Electronic goods","cameras-4",180.0,0.0,"Sony Cybershot W830 20.1MP Digital Camera","2 Year Sony India Warranty?20.1 Megapixel?2.7 inch LCD Screen?ISO 1600 - 6400 Sensitivity?CCD Image Sensor?HD Recording?Carl Zeiss Lens?f/3.3 - f/8.0 Aperture?HAD CCD Sensor?Sweep Panoroma Feature?SUPC: SDL275938723?",null));
 list.add(new Item("Electronic goods/cameras/Sony Cybershot WX80 16.2MP Digital Camera.jpg","Electronic goods","cameras-5",200.0,0.0,"Sony Cybershot WX80 16.2MP Digital Camera","Exmor® R CMOS Image Sensor?8x Optical Zoom?Built-In Wi-Fi?Full HD Recording?2.7 inches TFT LCD Screen?Intelligent Sweep Panorama?",null));
//cellphones
 list.add(new Item("Electronic goods/cellphones/Apple® - iPhone 6 16GB - Space Gray (Verizon Wireless).jpg","Electronic goods","cellphones-1",600.0,0.0,"Apple® - iPhone 6 16GB - Space Gray (Verizon Wireless)","4.7-inch (diagonal) Retina HD display with 1334-by-750 resolution?A8 chip with M8 motion coprocessor?8MP iSight camera with Focus Pixels and True Tone flash?1080p HD video recording at 60 fps and slo-mo video recording at 240 fps?FaceTime HD camera?Touch ID fingerprint sensor?LTE¹ and 802.11ac Wi-Fi?iOS 8 and iCloud",null));
 list.add(new Item("Electronic goods/cellphones/HTC - One (M8) 4G LTE Cell Phone with 32GB Memory - Gunmetal (Sprint).jpg","Electronic goods","cellphones-2",300.0,0.0,"HTC - One (M8) 4G LTE Cell Phone with 32GB Memory - Gunmetal (Sprint)","Qualcomm Snapdragon 801 processor?Android 4.4 KitKat OS?4G LTE speed?HTC Duo Camera with UltraPixels?HTC BoomSound with dual front-facing stereo speakers and built-in amplifiers deliver sound with less distortion?",null));
 list.add(new Item("Electronic goods/cellphones/LG - G3 Cell Phone - Shine Gold (Sprint).jpg","Electronic goods","cellphones-3",400.0,0.0,"LG - G3 Cell Phone - Shine Gold (Sprint)","Qualcomm Snapdragon 801 processor?Android 4.4 KitKat OS?4G LTE speed?5.5 Quad HD touch-screen display?13MP rear-facing camera with laser auto focus and OIS?32GB internal memory plus microSDHC slot?LG Health tracking?Unlock your phone quickly and securely?Access to Google Play?",null));
 list.add(new Item("Electronic goods/cellphones/Motorola - DROID Turbo 4G LTE with 32GB Memory Cell Phone - Blue (Verizon Wireless).jpg","Electronic goods","cellphones-4",350.0,15.0,"Motorola - DROID Turbo 4G LTE with 32GB Memory Cell Phone - Blue (Verizon Wireless)","Qualcomm Snapdragon 805 processor?Android 4.4 KitKat OS?4G LTE speed?5.2\" Super AMOLED HD touch screen?21.0MP rear-facing camera with HD recording?32GB internal memory?Use your smartphone as a mobile hotspot?Listen to your favorite tunes?",null));
 list.add(new Item("Electronic goods/cellphones/Samsung - Galaxy S6 4G with 32GB Memory Cell Phone - Black Sapphire.jpg","Electronic goods","cellphones-5",500.0,0.0,"Samsung - Galaxy S6 4G with 32GB Memory Cell Phone - Black Sapphire","Samsung Exynos Octa-Core processor?Android 5.0 Lollipop operating system?4G LTE speed?Bluetooth enabled?Dual-band 2.4GHz/5.0GHz Wi-Fi network (802.11a/b/g/n/ac)?5.1\" Super AMOLED touch screen?32GB internal memory?16.0MP rear-facing and 5.0MP front-facing cameras?",null));
 //computers
// list.add(new Item("Electronic goods/computers/ASUS Intel Core i3 4150T (3.0GHz) 4GB DDR3 500GB HDD 20 All-in-One PC.jpg","Electronic goods","computers-1",2500.0,5.0,"ASUS Intel Core i3 4150T (3.0GHz) 4GB DDR3 500GB HDD 20\" All-in-One PCWindows 7 Professional 64-Bit A4310-B1","Intel Core i3 4150T (3.0GHz)?4GB DDR3 500GB HDD?20\" 1600 x 900?Windows 7 Professional 64-Bit?Intel HD Graphics 4400?",null));
// list.add(new Item("Electronic goods/computers/Acer Aspire Intel Core i3 3227U (1.90GHz) 4GB DDR3 1TB HDD 23 All-in-One PC.jpg","Electronic goods","computers-2",3000.0,15.0,"Acer Aspire Intel Core i3 3227U (1.90GHz) 4GB DDR3 1TB HDD 23\" All-in-One PC Windows 8.1 64-Bit AZ3-605-UR2A","Intel Core i3 3227U (1.90GHz)?4GB DDR3 1TB HDD?23\" 1920 x 1080?Windows 8.1 64-Bit?Intel HD Graphics 4000?",null));
// list.add(new Item("Electronic goods/computers/DELL Inspiron Intel Core i3 4150 (3.50GHz) 8GB DDR3 1TB HDD 23 Touchscreen All-in-One PC.jpg","Electronic goods","computers-3",3500.0,15.0,"DELL Inspiron Intel Core i3 4150 (3.50GHz) 8GB DDR3 1TB HDD 23\" Touchscreen All-in-One PC Windows 8.1 64-Bit 5348 (i5348-4446BLK)","High def view?Stunning edge-to-edge touch?Faster everything?Easy connections?",null));
//list.add(new Item("Electronic goods/computers/LG Chromebase 2GB DDR3L 16GB SSD (Sandisk) HDD 21.5 All-in-One Google Chrome OS 22CV241-W.jpg","Electronic goods","computers-4",3500.0,10.0,"LG Chromebase 2GB DDR3L 16GB SSD (Sandisk) HDD 21.5\" All-in-One Google Chrome OS 22CV241-W","Intel Celeron processor?2GB DDR3L 1333?16GB SSD (Sandisk)?21.5\" 1920 x 1080 IPS?Google Chrome OS?1.3 MP Webcam?",null));
//list.add(new Item("Electronic goods/computers/Lenovo C260 Touch Pentium J2900 (2.41GHz) 4GB DDR3 500GB HDD 19.5 Touchscreen All-in-One PC.jpg","Electronic goods","computers-5",2500.0,15.0,"Lenovo C260 Touch Pentium J2900 (2.41GHz) 4GB DDR3 500GB HDD 19.5\" Touchscreen All-in-One PC Windows 8.1 64-bit 57327041","19.5” HD+ display (1600 x 900)?10-point capacitive touch technology?Space-saving all-in-one design?Front facing stereo speakers?Integrated DVD RW?USB AccuType keyboard?720p HD webcam?Lenovo Rescue System - a simple and quick way to backup and restore your data?",null));
//tv
list.add(new Item("Electronic goods/Tv/LG 47LB6500 119.38 cm (47) 3D Full HD Smart LED Television.jpg","Electronic goods","Television-1",800.0,00.0,"LG 47LB6500 119.38 cm (47) 3D Full HD Smart LED Television","Model:LG 47LB6500?Display Size:119.38 cm (47)?Display feature:3D Full HD?Screen Resolution:1920 x 1080p?In the box:Main Unit, 4 Basic 3D Glasses, Magic Remote Built-In, Conventional Remote (Optional)?Aspect Ratio:8 modes (16:9, Just scan, Original, Full Wide, 4:3, 14:9, Zoom,Cinema Zoom)?Dynamic Ratio:500000?Refresh Rate:200HZ?",null));
list.add(new Item("Electronic goods/Tv/Micromax 24B600HD 60 cm (24) HD Ready LED Television.jpg","Electronic goods","Television-2",700.0,0.0,"Micromax 24B600HD 60 cm (24) HD Ready LED Television","Model:24B600HD?Screen Type:LED?Display Size:60 cm (24)?Display Feature:HD Ready; TFT Display?Screen Resolution:1366 x 768?Aspect Ratio:16:09?Additional:Brightness: 250 cd/m2; Contrast Ratio: 3000000:1; Analog TV Reception: M/N, PAL/SECAM/NTSC, B/G, I, D/K, NTSC/PAL; Backlight Module: Edge LED; Color Control; Zoom; 8.5ms Response Time?",null));
list.add(new Item("Electronic goods/Tv/Samsung 23H4003 58 cm (23) HD Ready LED Television.jpg","Electronic goods","Television-3",650.0,10.0,"Samsung 23H4003 58 cm (23) HD Ready LED Television","Model:23H4003?Screen Resolution:1366 x 768 Pixels?Dynamic Ratio:Mega Contrast?Refresh Rate:100 Hz Clear Motion Rate?",null));
list.add(new Item("Electronic goods/Tv/Sony BRAVIA 48W600B 121 cm (48) Full HD Smart LED Television.jpg","Electronic goods","Television-4",550.0,0.0,"Sony BRAVIA 48W600B 121 cm (48) Full HD Smart LED Television","Experience Stunning Picture Details With C-Reality PRO?Full HD Video Quality For Ultimate Entertainment?Crystal Clear Audio Quality?One-Flick Entertainment For All Your Demands?Enjoy Wide Range Of Content With Internet TV?Built-in Wireless LAN For Greater Connectivity and Entertainment?Supersize Your Mobile Content Screen Mirroring?",null));
list.add(new Item("Electronic goods/Tv/Sony BRAVIA KLV-22P402B 54.7 cm (22) Full HD LED Television.jpg","Electronics goods","Television-5",850.0,0.0,"Sony BRAVIA KLV-22P402B 54.7 cm (22) Full HD LED Television","Model:KLV 22P402B-Display Size:Display Size-55.88 cm (22)-Screen Resolution:1920 x 1080-Aspect Ratio:TV: Auto Wide/ Full/ Normal/ Wide Zoom/ Zoom/ PC HDMI: Full 1/ Full 2/ Normal/ 4:3 Default-View Angle:Horizontal: 85 Degree, Vertical: 80 Degree-Headphone Out:1 (Rear/Hybrid with Audio Out)",null));
//Home theater
list.add(new Item("Electronic goods/home theater/RCA RT2781H 5.1 Home Theater System - 1000 W RMS.jpg","Electronic goods","hometheater-1",500.0,0.0,"RCA RT2781H 5.1 Home Theater System - 1000 W RMS","1,000W MAX POWER115.1 CHANNEL113 HDMI INPUTS & 1 HDMI OUTPUT1111OPTICAL & COAXIAL DIGITAL AUDIO INPUTS11RCA INPUT112 RCA INPUTS11AUX INPUT11DOLBY(R) AM/FM TUNER WITH STATION MEMORY PRESETS11",null));
list.add(new Item("Electronic goods/home theater/RCA RT2911 1,000-Watt Home Theater System.jpg","Electronic goods","hometheater-2",400.0,0.0,"RCA RT2911 1,000-Watt Home Theater System","1,000W power11145W x 4 & 210W x 211Full HDMI(R) switching allows users to play HDMI(R) audio from selected HDMI(R) input, while also passing through the HDMI(R) signal to TV113 HDMI(R) inputs, 1 HDMI(R) output11 Digital optical & coaxial audio inputs11 3 aux audio inputs11 Aux input for iPod(R) & other portable audio products11 6.5mm headphone output11Small speaker size11 Digital AM/FM tuner with 30 AM/30 FM station presets",null));
list.add(new Item("Electronic goods/home theater/Samsung HT-H6500WM Home Theater System.jpg","Electronic goods","hometheater-3",550.0,0.0,"Samsung HT-H6500WM Home Theater System","Smart hub11Full webbrowser1111Builtin wifi11Wireless rear speaker11Bluetooth11Crystal amp-plus113D blu-ray11surround sound11Dolby digital plus11Dolby true HD",null));
 list.add(new Item("Electronic goods/home theater/YAMAHA YHT-399UBL 5.1-Channel Home Theater in a Box.jpg","Electronic goods","hometheater-4",450.0,0.0,"YAMAHA YHT-399UBL 5.1-Channel Home Theater in a Box","Five-channel powerful surround sound (100W per channel)11HD Audio format decoding: Dolby® TrueHD and DTS-HD Master Audio11Dolby Digital Plus and DTS-HD High Resolution Audio11Discrete amplifier technology11192kHz / 24-bit Burr-Brown DACs for all channels11High dynamic power, low-impedance drive capability11Two-way speaker drivers for high power input capacity118in. 100W active subwoofer",null));
 list.add(new Item("Electronic goods/home theater/YAMAHA YHT-4910U AV Home Theater System.jpg","Electronic goods","hometheater-5",350.0,0.0,"YAMAHA YHT-4910U AV Home Theater System","5-Channel powerful surround sound11100W per channel (8 Ohms, 1kHz, 0.9% THD, 1-ch driven)1170W per channel (8 Ohms, 20Hz - 20kHz, 0.09% THD, 2-Ch. driven)11Discrete amp configuration11HDMI® (4 in / 1 out) with 4K Ultra HD pass-through for super high resolution images11Front panel USB digital connection for iPod® and iPhone®11Virtual CINEMA FRONT provides virtual surround sound with five speakers in front11Extra Bass enriches powerful bass sound even with small speakers11YPAO™ sound optimization for automatic speaker set up11Multilingual color OSD for improved visibility (English, German, French, Spanish, Russian, Italian, Japanese and Chinese)11ECO mode operation for about 20 percentage less power consumption11",null));
 
 //                 Fashion              //
 //skirts
 list.add(new Item("Fashion/Skirts/Apricot Elastic Waist Multilayers Mesh Skirt.jpg","Fashion","Skirt-1",50.0,0.0,"Apricot Elastic Waist Multilayers Mesh Skirt","Length(cm) :75cm11Waist Size(cm) :62-88cm11Size Available :one-size11Pattern Type :Plain11Silhouette :Pleated11Dresses Length :Knee Length11Color :Apricot11Material :Tulle11Style :Street11",null));
 list.add(new Item("Fashion/Skirts/Black Elastic Waist Polka Dot Pleated Skirt.jpg","Fashion","Skirt-2",40.0,0.0,"Black Elastic Waist Polka Dot Pleated Skirt","Size Available :One Size11Length(cm) :70cm11Pattern Type :Polka Dot11Silhouette :Pleated11Dresses Length :Knee Length11Color :Black11Material :Chiffon11Style :Street11",null));
 list.add(new Item("Fashion/Skirts/Multicolor High Waist Floral Skirt.jpg","Fashion","Skirt-3",60.0,0.0,"Multicolor High Waist Floral Skirt","Size Available :S,M,L11Length(cm) :S:60cm,M:61cm,L:62cm11Waist Size(cm) :S:72cm,M:76cm,L:80cm11Pattern Type :Floral11Silhouette :A Line11Dresses Length :Knee Length11Color :Multi11Material :Cotton Blends11Style :Street11",null));
 list.add(new Item("Fashion/Skirts/Navy Floral Birds Print Pleated Skirt.jpg","Fashion","Skirt-4",40.0,0.0,"Navy Floral Birds Print Pleated Skirt","Size Available :One Size11Length(cm) :88cm11Waist Size(cm) :64-104cm11Pattern Type :Print11Silhouette :Pleated11Dresses Length :Long/Full Length11Color :Navy11Material :Chiffon11Style :Street11",null));
 list.add(new Item("Fashion/Skirts/Red Vintage Floral Mesh Skirt.jpg","Fashion","Skirt-5",30.0,0.0,"Red Vintage Floral Mesh Skirt","Length(cm) :XS:58cm,S:59cm,M:60cm,L:61cm,XL:62cm,XXL:63cm11Waist Size(cm) :XS:60cm,S:64cm,M:68cm,L:72cm,XL:76cm,XXL:80cm11Pattern Type :Floral11Silhouette :Pleated11Dresses Length :Knee Length11Color :Red11Material :Polyester11Style :Fashion11",null));
 
 //Sweaters
 list.add(new Item("Fashion/Sweaters/Black Long Sleeve Diamond Cardigan Sweater.jpg","Fashion","Sweater-1",55.0,0.0,"Black Long Sleeve Diamond Cardigan Sweater","Size Available :one-size11Sleeve Length(cm) :59cm11Length(cm) :73cm11Bust(cm) :96cm11Season :Fall11Pattern Type :Geometric11Items :Cardigan11Color :Black11Types :Loose11Sleeve Length :Long Sleeve11Material :Acrylic11Styles :Casual11",null));
  list.add(new Item("Fashion/Sweaters/Black Long Sleeve Dipped Hem Knit Sweater.jpg","Fashion","Sweater-2",50.0,0.0,"Black Long Sleeve Dipped Hem Knit Sweater","Size Available :one-size11Sleeve Length(cm) :67cm11Length(cm) :51/57cm11Bust(cm) :114cm11Season :Fall11Pattern Type :Plain11Items :Pullovers11Color :Black11Types :Loose11Sleeve Length :Long Sleeve11Neckline :Round Neck11Material :Knit11Styles :Casual11",null));
  list.add(new Item("Fashion/Sweaters/Khaki Long Sleeve Faux Fur Lapel Cardigan Sweater.jpg","Fashion","Sweater-3",35.0,0.0,"Khaki Long Sleeve Faux Fur Lapel Cardigan Sweater","Length(cm) :78cm11Bust(cm) :92cm11Size Available :one-size11Sleeve Length(cm) :60cm11Season :Fall11Pattern Type :Plain11Items :Cardigan11Color :Khaki11Types :Loose11Sleeve Length :Long Sleeve11Neckline :Lapel11Material :Acrylic11",null));
  list.add(new Item("Fashion/Sweaters/Red Lapel Long Sleeve Ouch Cardigan Sweater.jpg","Fashion","Sweater-4",40.0,0.0,"Red Lapel Long Sleeve Ouch Cardigan Sweater","Bust(cm) :98cm11Shoulder(cm) :54cm11Size Available :one-size11Sleeve Length(cm) :48cm11Length(cm) :58cm11Season :Fall11Pattern Type :Plain11Items :Coat11Color :Red11Types :Loose11Sleeve Length :Long Sleeve11Neckline :Turtleneck11Material :Cotton Blends11Styles :Casual11",null));
  list.add(new Item("Fashion/Sweaters/White Long Sleeve Striped Knit Sweater.jpg","Fashion","Sweater-5",30.0,0.0,"White Long Sleeve Striped Knit Sweater","Shoulder(cm) :36cm11Size Available :One Size11Sleeve Length(cm) :55cm11Length(cm) :57cm11Bust(cm) :92cm11Season :Fall11Pattern Type :Striped11Items :Pullovers11Color :White11Types :Loose11Sleeve Length :Long Sleeve11Neckline :Round Neck11Material :Cotton Blends11Styles :Casual11",null));
  
  //dresses
  list.add(new Item("Fashion/dresses/CREPE STRAP DETAIL ASYMMETRIC DRESS BLACK.jpg","Fashion","dresses-1",30.0,0.0,"CREPE STRAP DETAIL ASYMMETRIC DRESS BLACK","Give your Little Black Dress collection an update with this chic black crepe dress. With luxe strap detail this textured bodycon beauty with asymmetric hem will give you a standout look this season. Team with nude strappy heels and matching clutch for a touch of evening class11Approx length 102cm/40” (Based on a UK size 8 sample)1195% Polyester 5% Elastane11Cindy wears a UK size 8/ EU size 36/ US size 4 and her height is 5'911",null));
  list.add(new Item("Fashion/dresses/JEANETTE HIGH NECK SWING DRESS GREY.jpg","Fashion","dresses-2",35,0.0,"JEANETTE HIGH NECK SWING DRESS GREY","Swing into style this season with this chic grey knitted swing dress. With luscious long sleeves, super soft fabric and a fierce high neck this dress is a beaut. Team with statement ankle boots and a checked shirt tied around the waist for mega Off Duty vibes11Approx length 89cm/35\" (Based on a UK size 8 sample)1195% Polyester 5% Elastane11Emily wears a UK size 8 and her height is 5'1111",null));
  list.add(new Item("Fashion/dresses/POM POM TRIM BELL SLEEVE SWING DRESS BLACK.jpg","Fashion","dresses-3",25.0,0.0,"POM POM TRIM BELL SLEEVE SWING DRESS BLACK","Work that black jersey swing dress this season. With fierce flared long sleeves and totally dreamy pom-pom trim this dress is a must-have addition to your wardrobe. Team with ankle boots and heaping’s of jewellery for a luscious finish.11Approx length 84cm/33” (Based on a UK size 8 sample)1195% Polyester 5% Elastane11Joanna wears a UK size 8 / EU size 36 / US size 4 and her height is 5'711",null));
  list.add(new Item("Fashion/dresses/SLINKY MAXI DRESS NUDE.jpg","Fashion","dresses-4",30.0,0.0,"SLINKY MAXI DRESS NUDE","We are lusting over slinky fabrics this season and this nude maxi dress is a total dream. With high strappy neckline this nude beauty infused with metallic will give you a seriously standout figure. Team with matching nude strappy heels and box clutch for evening luxe.11Approx length 145cm/57\" (Based on a UK size 8 sample)1195% Polyester 5% Elastane11Cindy wears a UK size 8 / EU size 36 / US size 4 and her height is 5'911",null));
  list.add(new Item("Fashion/dresses/STRIPE DUNGAREE ROMPER CREAM.jpg","Fashion","dresses-5",30.0,0.0,"STRIPE DUNGAREE ROMPER CREAM","Refresh your wardrobe for a hit of minimalist styling. This stripe dungaree romper is a new season winner - effortless, clean and fresh comes to mind. Featuring adjustable straps, button details and turn up design so you can pull of the Style Edit trend in an instant with this beauty. Team with a black crop top, flatforms and a cool hat to work the look.11Approx length 73cm/29” (Based on a UK size 8 sample)11100% Polyester\n11Emily wears a UK size 8/ EU 36/ US 6 and her height is 5'111",null));

  //outwears
list.add(new Item("Fashion/outerwears/Chic Solid Long-Sleeve Oversized Longline Coat.jpg","Fashion","outerwears-1",25.0,0.0,"Chic Solid Long-Sleeve Oversized Longline Coat","INCH11S:Shoulder:13½,Sleeve:23¼,Length:30,Bust:37¼11M:  Shoulder:14,Sleeve:23¾,Length:30½,Bust:38¾11L:   Shoulder:14¼,Sleeve:24¼,Length:30¾,Bust:40¼\n11:11S:Shoulder:34,Sleeve:59,Length:76,Bust:9411M:  Shoulder:35,Sleeve:60,Length:77,Bust:9811L:Shoulder:36,Sleeve:61,Length:78,Bust:102",null));
list.add(new Item("Fashion/outerwears/Fashion Warm Plaid Open Front Black Woolen Coat.jpg","Fashion","outerwears-2",20.0,0.0,"Fashion Warm Plaid Open Front Black Woolen Coat","INCH11one size:Sleeve:12¼,Length:30,Bust:55¼11one size:Sleeve:32,Length:76,Bust:14011",null));
list.add(new Item("Fashion/outerwears/Floral Graphic Black Bomber Jacket.jpg","Fashion","outerwears-3",35.0,0.0,"Floral Graphic Black Bomber Jacket","INCH11S:   Sleeve:22½,Length:21¾,Bust:35½11M:  Sleeve:23¼,Length:22½,Bust:36¼11L:   Sleeve:24¼,Length:23¼,Bust:37¼\11S:   Sleeve:57,Length:55,Bust:9011M:  Sleeve:59,Length:57,Bust:9211L:   Sleeve:61,Length:59,Bust:9411",null));
list.add(new Item("Fashion/outerwears/Luxe Netted Pattern Jacket.jpg","Fashion","outerwears-4",55.0,0.0,"Luxe Netted Pattern Jacket","INCH11S:   Shoulder:14¼,Sleeve:23,Length:21¾,Bust:37¼11M:  Shoulder:15,Sleeve:23¾,Length:22½,Bust:39½11L:   Shoulder:15¾,Sleeve:24½,Length:23¼,Bust:4111S:   Shoulder:36,Sleeve:58,Length:55,Bust:9611M:  Shoulder:38,Sleeve:60,Length:57,Bust:10011L:   Shoulder:40,Sleeve:62,Length:59,Bust:10411",null));
list.add(new Item("Fashion/outerwears/Stylish Olive Green Faux Fur Collar Coat.jpg","Fashion","outerwears-5",45.0,0.0,"Stylish Olive Green Faux Fur Collar Coat","INCH11S:   Shoulder:14¼,Sleeve:23¾,Length:29¾,Bust:37¼11M:  Shoulder:14¾,Sleeve:24¼,Length:30,Bust:38¾11L:   Shoulder:15,Sleeve:24½,Length:30½,Bust:40¼11S:   Shoulder:36,Sleeve:60,Length:75,Bust:9411M:  Shoulder:37,Sleeve:61,Length:76,Bust:9811L:   Shoulder:38,Sleeve:62,Length:77,Bust:10211",null));
  
//pants
list.add(new Item("Fashion/pants/Billy London Suit Separates Black Solid Pants.jpg","Fashion","pants-1",50.0,0.0,"Billy London Suit Separates Black Solid Pants","Update your wardrobe with these Suit Separates black pants from Billy London. The pants have a flat front, stylish seam on the pockets for a streamlined look.11Color: Black11Fit: Slim11Solid print11Two (2) back pockets11Zip fly with hook closure11Flat front11Hemmed bottom11",null));
list.add(new Item("Fashion/pants/Brooklyn Xpress Men's Belted Fashion Denim Jean.jpg","Fashion","pants-2", 50.0,0.0,"Brooklyn Xpress Men's Belted Fashion Denim Jean","Printed web belt with dual loop metal closures, riveted pockets, constrast stitch detail11Color: Black11Fit: Slimmer cut straight leg11Pockets: Two (2) front pockets, one (1) coin pocket, two (2) rear patch pockets11Waist details: Constructed waist with belt loops/ button11Type of fly: Zipper with button at waist11Hem situation: Hemmedm11",null));
list.add(new Item("Fashion/pants/Cianni Cellini Men's Navy Wool Gabardine Pants.jpg","Fashion","pants-3",45.0,0.0,"Cianni Cellini Men's Navy Wool Gabardine Pants","Color options: Navy11Fit: Men's 11Pockets: Two (2) front pockets, two (2) button back pockets11Waist details: Belt loops11Type of fly: Zip fly11Hem situation: Unhemmed11",null));
list.add(new Item("Fashion/pants/Cianni Cellini Men's Tan Wool Gabardine Pants.jpg","Fashion","pants-4",50.0,15.0,"Cianni Cellini Men's Tan Wool Gabardine Pants","Color options: Tan11Fit: Men's11Pockets: Two (2) front pockets, two (2)button back pockets11Waist details: Belt loops11Type of fly: Zip fly11Hem situation: Unhemmed11",null));
list.add(new Item("Fashion/pants/Men's Taupe Flat-front Wool Dress Pants.jpg","Fashion","pants-5",45.0,0.0,"Men's Taupe Flat-front Wool Dress Pants","Crafted in soft, virgin wool, these dress pants offer comfort and enduring style to any man's wardrobe.11Classic fit11Taupe color option11Lined to the knee11Front slant pockets11Two back pockets with button closure11Flat front11Unhemmed for customization11",null));

                                
//           Hand bags                      //
//buckets and sags
list.add(new Item("Handbags/Buckets and sacs/As Is Dooney & Bourke Nubuk Leather O-Ring Sac.jpg","Handbags","Buckets and sacs-1",25.0,0.0,"As Is\" Dooney & Bourke Nubuk Leather O-Ring Sac","Nubuk body, adjustable strap with O-ring details, leather logo patch, magnetic closure, four bottom feet11Fully lined interior, back-wall zip and slip pockets, two front-wall slip pockets, key keeper11Measures approximately 12-1/2\"W x 10\"H x 5-1/2\"D with a 12\" to 14\" strap drop; weighs approximately 2 lbs, 9 oz11Body/trim 100% genuine leather; lining 100% cotton11Imported",null));
list.add(new Item("Handbags/Buckets and sacs/Dooney & Bourke Nubuck Leather O-Ring Sac.jpg","Handbags","Buckets and sacs-2",100.0,0.0,"Dooney & Bourke Pebble Leather Zip Sac","Even the most die-hard purse lover has one bag that she gravitates towards again and again. Odds are, this soft, roomy nubuk sac is going to become that bag for you--especially since the O-ring strap adjusts so it doesn't have to go into hibernation when the winter coats come out. From Dooney & Bourke.11Nubuk body, adjustable strap with O-ring details, leather logo patch, magnetic closure, four bottom feet11Fully lined interior, back-wall zip and slip pockets, two front-wall slip pockets, key keeper11Measures approximately 12-1/2\"W x 10\"H x 5-1/2\"D with a 12\" to 14\" strap drop; weighs approximately 2 lbs, 9 oz11Body/trim 100% genuine leather; lining 100% cotton11Imported",null));
list.add(new Item("Handbags/Buckets and sacs/Dooney & Bourke Pebble Leather Zip Sac.jpg","Handbags","Buckets and sacs-3",50.0,0.0,"Dooney & Bourke Nubuck Leather O-Ring Sac","A touch of texture. This Dooney & Bourke sac drops an intricate touch into your casual wardrobe with its rich pebble leather exterior, while a single shoulder strap allows for easy wear. From Dooney & Bourke.11Pebble leather, adjustable strap, two front exterior zip pockets, one back exterior zip pocket, leather logo patch, four bottom feet, top zip closure11Lined interior, two front slip pockets, one back zip, one back slip pocket, and key keeper11Measures approximately 13-3/4\"W x 10\"H x 6\"D with a 21\" to 24\" strap drop; weighs approximately 2 lbs, 9oz11Body/trim 100% leather; lining 100% cotton11Imported",null));
list.add(new Item("Handbags/Buckets and sacs/Dooney & Bourke Pebble Leather Small Sac with Key Fob.jpg","Handbags","Buckets and sacs-4",60.0,0.0,"Dooney & Bourke Pebble Leather Small Sac with Key Fob","Simplify the morning rush. Whether you're running out the door to work or to the store for a few quick errands, this small sac and key fob help you carry the essentials you need. The pebble-textured leather is beautifully contrasted by the trim and handle for signature appeal. From Dooney & Bourke11Pebble leather, key fob, outside zip pocket, shoulder strap with chain detail, zip top closure, burnished hardware11Lined interior, back wall zip pocket and slip pocket, two front-wall slip pockets11Measures 15\"W x 9\"H x 5\"D with a 5\" strap drop; weighs approximately 1 lb, 12 oz11Body/trim 100% leather; lining 100% cotton11Made in China11",null));
list.add(new Item("Handbags/Buckets and sacs/Kelsi Dagger Avery Dip-Dyed Long Shoulder Bucket Bag.jpg","Handbags","Buckets and sacs-5",30.0,0.0,"Kelsi Dagger Avery Dip-Dyed Long Shoulder Bucket Bag","Style: Avery11Dip-dyed, shoulder strap with woven detail, zippered top closure with leather pull, structured bottom11Lined interior, two front-wall slip pockets; one back-wall zippered pocket11Measures approximately 12\"W x 13\"H x 5\"D with an 18\" strap drop; weighs approximately 1 lb11Body/trim 100% leather; lining 100% nylon11Made in China11",null));

//crossbody bags//
list.add(new Item("Handbags/Crossbody bags/Fossil Explorer Straw Cross Body Bag.jpg","Handbags","Crossbody bags-1",20.0,0.0,"Fossil Explorer Straw Cross Body Bag","61.9% Jute/38.1% Polyethylene11Imported11polyester lining11zipper closure1121\" shoulder drop119\" high1111.25\" wide11Signature jacquard lining - 100 polyester interior11Interior features two media pockets and one zipper pocket11Exterior features two zipper pockets11Zip closure1120.25 drop length11Made in China",null));
list.add(new Item("Handbags/Crossbody bags/kate spade new york Cobble Hill Straw Mini Carson Cross Body Bag.jpg","Handbags","Crossbody bags-2",30.0,0.0,"kate spade new york Cobble Hill Straw Mini Carson Cross Body Bag","100% Polyethylene11Imported11polyester lining11zipper closure11Made in China11",null));
list.add(new Item("Handbags/Crossbody bags/Steve Madden Bcharlee Mini Cross Body.jpg","Handbags","Crossbody bags-3",20.0,0.0,"Steve Madden Bcharlee Mini Cross Body","100% Polyurethane11Imported11100% Polyester lining11Twist-Lock closure1122\" shoulder drop114.5\" high116.5\" wide11One interior zip pocket11Made in China11",null));
list.add(new Item("Handbags/Crossbody bags/Ted Baker Domina Distnguish Rose XHTCH Lady Bag.jpg","Handbags","Crossbody bags-4",20.0,0.0,"Ted Baker Domina Distnguish Rose XHTCH Lady Bag","100% Polyvinyl Chloride11Imported11100% Polyester lining11Snap closure1123\" shoulder drop117\" high119.25\" wide11One interior zip and three slip pockets11Made in China11",null));
list.add(new Item("Handbags/Crossbody bags/T-Shirt & Jeans Small Cross Body Bag.jpg","Handbags","Crossbody bags-5",20.0,0.0,"T-Shirt & Jeans Small Cross Body Bag","Polyurethane11Imported11Polyester lining11Zipper closure1126\" shoulder drop117.5\" high1110\" wide11Exterior pocket. One interior zip and two slip pockets11Made in China11",null));

//hobos
list.add(new Item("Handbags/Hobos/Amerileather Cynthia Handbag.jpg","Handbags","Hobos-1",45.0,0.0,"Amerileather Cynthia Handbag","Handbag Material:Leather11Handbag Color:Purple Red11Dimensions:Approx 17 in. L x 17 in. H x 4.25 in.W11Materials:Top Grain Cowhide Leather11Model Number:1805-18",null));
list.add(new Item("Handbags/Hobos/Coach Scout Pebbled Leather Hobo Bag.jpg","Handbags","Hobos-2",45.0,0.0,"Coach Scout Pebbled Leather Hobo Bag","Pebble leather11Color options: Black, nude11Style: Hobo bag11Construction: Leather11Exterior: Pebbled11Entry: Zip-top closure11Hardware: Goldtone11Lining: Logo-jacquard lining11Handles: Single11",null));
list.add(new Item("Handbags/Hobos/Dasein Fashion Hobo Bag.jpg","Handbags","Hobos-3",45.0,0.0,"Dasein Fashion Hobo Bag","Color options: Red, purple11Style: Hobo bag11Construction: Faux leather11Entry: Zip-top closure11Hardware: Silvertone11Lining: Fully lined11Handles: Double rolled11Exterior pockets: One (1) back zip11Interior pockets: One (1) side zip, one (1) cell phone pouch11Country of origin: Imported11Bag dimensions: 9.5 inches high x 17 inches wide x 5 inches deep11Drop: 6 inches11",null));
list.add(new Item("Handbags/Hobos/J. Furmani Women's High Quality Hobo Handbag.jpg","Handbags","Hobos-4",45.0,0.0,"J. Furmani Women's High Quality Hobo Handbag","Metal button accents in front11Color options: Black, brown11Style: Hobo bag11Construction: Vegan leather11Entry: Zip-top closure11Lining: Inside fabric lining11Handles: Double11Interior pockets: One (1) zippered pocket and two (2) media pockets11Bag dimensions: 14 inches high x 8 inches wide x 5 inches deep11Drop: 11 inches11",null));
list.add(new Item("Handbags/Hobos/Patched Corner Hobo Bag.jpg","Handbags","Hobos-5",45.0,0.0,"Patched Corner Hobo Bag","Color options: Blue, Green, Pink, Orange, White, Purple, Silver, Black, Coffee, Blackgreen, Red, Camel, Bronze, Pewter, Coral Red, Light Pink11Style: Hobo bag11Construction: Faux leather11Exterior: Straps connected by carabiner hooks11Entry: Magnetic closure11Hardware: Silvertone hardware11",null));

//Satchels
list.add(new Item("Handbags/Satchels/Ann Creek 'Moderna' Satchel Bag.jpg","Handbags","Satchels-1",50.0,0.0,"Ann Creek 'Moderna' Satchel Bag","Product features: Detachable, adjustable shoulder strap11Color options: Black, blue, red, yellow11Style: Satchel11Construction: Faux leather11Exterior: Solid color11Entry: Zip top closure11Hardware: Silvertone, protective metal foot based decorative lock11",null));
list.add(new Item("Handbags/Satchels/DimeCity 'Cranford' Satchel Bag.jpg","Handbags","Satchels-2",30.0,0.0,"DimeCity 'Cranford' Satchel Bag","Color options: Black/ ivory, yellow/ ivory11Style: Satchel bag11Construction: Man-made11Exterior: Two-tone, red trim11Entry: Magnetic top closure11Hardware: Goldtone11Lining: Black synthetic fabric11Handles: Double rolled11Interior pockets: One (1) zipper, two (2) clip11Country of origin: Imported11Bag dimensions: 10.5 inches high x 13 inches wide x 5 inches deep11",null));
list.add(new Item("Handbags/Satchels/Lithyc 'Avenue D' Medium Satchel.jpg","Handbags","Satchels-3",40.0,0.0,"Lithyc 'Avenue D' Medium Satchel","State: Utah11Color options: Black, coffee, red11Style: Satchel11Construction: Vegan leather11Entry: Zipper11Handles: Two (2) rolled handles11Hardware: Goldtone11Lining: Solid fabric11Exterior pockets: One (1) back zippered pocket11",null));
list.add(new Item("Handbags/Satchels/Mellow World Mia Satchel.jpg","Handbags","Satchels-4",60.0,0.0,"Mellow World Mia Satchel","Color options: Black, camel, fuchsia, green, pink11Style: Satchel11Construction: 100-percent faux leather11Entry: Zip-top closure11Handles: 5 inches11Detachable/ adjustable crossbody strap11Exterior pockets: 2 button slip pockets11Interior pockets: Four interior pockets11Bag dimensions: 13 inches x 6 inches x 9 inches11Drop: 5 inches11",null));
list.add(new Item("Handbags/Satchels/Olivia Miller Two-tone Satchel.jpg","Handbags","Satchels-5",45.0,0.0,"Olivia Miller Two-tone Satchel","Color options: Cognac, black/ white11Style: Satchel11Construction: PU11Exterior: Two-tone11Entry: Zip-top closure11Hardware: Goldtone11Lining: Polyester11Handles: Double handles, detachable/ adjustable strap11Interior pockets: Zip pocket, two (2) slip pockets11Bag dimensions: 7 inches high x 11 inches wide x 6.5 inches deep11Drop: 5 inches11",null));

//wallets
list.add(new Item("Handbags/wallets/Brandio Men's Leather Striped Bi-fold Wallet.jpg","Handbags","wallets-1",20.0,0.0,"Brandio Men's Leather Striped Bi-fold Wallet","Color options: Black, brown11Style: Exclusive leather wallet11 Material: Leather11Entry: Fold-over closure11Bi-fold/tri-fold: Bi-fold11Lining: Fabric lining11Dimensions: 110 mm long x 90 mm wide x 18 mm deep11Pockets/Slots/I.D. Window: Divided billfold, thumb-slide ID window, nine (9) credit card slots, removable business card holder",null));
list.add(new Item("Handbags/wallets/Dopp Men's Regatta ID Tri-fold Wallet.jpg","Handbags","wallets-2",30.0,0.0,"Dopp Men's Regatta ID Tri-fold Wallet","Rich Oil Tanned Cowhide11Lined currency section with divider11Removable 2 sided ID card case11Multiple card slots and11Two utility slip pockets",null));
list.add(new Item("Handbags/wallets/Guess Men's Distressed Embossed Bi-Fold Passcase Wallet.jpg","Handbags","wallets-3",20.0,0.0,"Guess Men's Distressed Embossed Bi-Fold Passcase Wallet","Color options: Black, brown11Style: Exclusive leather wallet11 Material: Leather11Entry: Fold-over closure11Bi-fold/tri-fold: Bi-fold11Lining: Fabric lining11Dimensions: 110 mm long x 90 mm wide x 18 mm deep11Pockets/Slots/I.D. Window: Divided billfold, thumb-slide ID window, nine (9) credit card slots, removable business card holder",null));
list.add(new Item("Handbags/wallets/NCAA Kentucky Wildcats Leather Embossed Bi-fold Wallet.jpg","Handbags","wallets-4",20.0,0.0,"NCAA Kentucky Wildcats Leather Embossed Bi-fold Wallet","Brand: Rico Industries11Color: Brown11Materials: Genuine cowhide leather11Entry: Bi-fold11Lining: Leather11Four credit card slots11Plastic picture insert11Comes in a metal gift tin11Dimensions: 4.5 inches wide by 3.5 inches long",null));
list.add(new Item("Handbags/wallets/TITAN Leather Men Formal Wallet.jpg","Handbags","wallets-5",20.0,0.0,"TITAN Leather Men Formal Wallet","Gender : Men11Type : Formal Wallet11Material : Leather11Wallet Closure : Bi-Fold11Brand : TITAN11SUPC: SDL02996229411",null));

//                     Shoes                        //
//boots
list.add(new Item("shoes/boots/Women's Blackstone Shoes CW66.jpg","shoes","boots-1",265.0,0.0,"Women's Blackstone Shoes CW66","Ankle strap with metal buckle closure11Approx. 10'' boot circumference11Approx. 1¼'' heel height11Approx. 9'' boot shaft height11Back zip entry with knotted leather pull11Blind eyelet-and-hook front lace closure11Cushioned footbed11Leather lining11Premium full-grain leather and suede upper11Synthetic traction sole11",null));
list.add(new Item("shoes/boots/Women's Circus By Sam Edelman Randi Riding Boot.jpg","shoes","boots-2",165.0,0.0,"Women's Circus By Sam Edelman Randi Riding Boot","Leather and faux leather upper in a riding boot style11Round toe11Shaft can fold down or up11Outside full length zip closure11Buckled strap overlay11Textile lining with a cushioning footbed11Traction outsole1115 inch shaft height, 14 ½ inch circumference11 1 inch heel11",null));
list.add(new Item("shoes/boots/Women's Seychelles Outspoken Boot.jpg","shoes","boots-3",125.0,0.0,"Women's Seychelles Outspoken Boot","Leather and suede upper in a dress knee high boot style11Pointed toe11Full length inside zip closure11Smooth lining with a cushioning footbed11Traction outsole11 14 ½ inch shaft height, 14 ½ inch circumference113 ½ inch heel11",null));
list.add(new Item("shoes/boots/Women's UGG® Australia Classic Short.jpg","shoes","boots-4",105.0,0.0,"Women's UGG® Australia Classic Short","Approx. 7'' boot shaft height11Cushion footbed11Rubber sole (pattern may vary)11Sheepskin upper11Twinface sheepskin lining11",null));
list.add(new Item("shoes/boots/Women's Volatile Griggs Riding Boot.jpg","shoes","boots-5",120.0,0.0,"Women's Volatile Griggs Riding Boot","Faux leather upper in a knee high riding boot style11Round toe11Inside zip closure11Full length elastic goring panel11Buckled strap overlay11Textile lining with a cushioning footbed11Traction outsole1114 inch shaft height, 14 ½ inch circumference111/4 inch heel11",null));

//flats
list.add(new Item("shoes/flats/Bonnibel 'Great-5' Women's Sparkling Glitter Slip-on Ballet Flats.jpg","shoes","flats-1",120.0,0.0,"Bonnibel 'Great-5' Women's Sparkling Glitter Slip-on Ballet Flats","Color options: Black, champagne, silver11Style: Flats11Material: Glitter faux leather11Toe shape: Round11Heel height/ type: 0. 25-inch11Width: Medium11Lining: Unlined11Sole: Man-made, textured sole11Footbed: Padded11Imported11",null));
list.add(new Item("shoes/flats/Journee Collection Women's 'Pansy' Ankle Strap Cut-out Flats.jpg","shoes","flats-2",120.0,0.0,"Journee Collection Women's 'Pansy' Ankle Strap Cut-out Flats","Color options: Black, neutral, white,11Style: Flats11Material: PU leather11Toe shape: Round11Heel height/type: 0.58-inch block11Platform height: 0.39 -inch11Width: Medium11Lining: No lining11Sole: Man-made, textured11Footbed: Slightly padded11Imported11",null));
list.add(new Item("shoes/flats/MACHI NOVA Women's Glitter Ballet Flats (2).jpg","shoes","flats-3",50.0,65.0,"MACHI NOVA Women's Glitter Ballet Flats (2)","Product Features: N/A11Material: Faux Leather, Patent Leather11Style: Loafer11Shoe Width: Medium11Exact Color: Black, Gold, Silver11Size: 10, 5.5, 8.5, 7, 6, 6.5, 7.5, 9, 811Color: Black, Gold, Silver",null));
list.add(new Item("shoes/flats/MACHI SPRING Women's Floral Flat Shoes.jpg","shoes","flats-4",90.0,0.0,"MACHI SPRING Women's Floral Flat Shoes","Product Features: N/A11Material: Faux Leather11Style: Peep Toe11Shoe Width: Medium11Exact Color: Camel, Blue, Black, Pink11Size: 10, 5.5, 8.5, 7, 6, 6.5, 7.5, 9, 811Color: Blue, Tan, Black, Pink11",null));
list.add(new Item("shoes/flats/Refresh Women's 'Demi'-05' Round-toe Ballet Flats.jpg","shoes","flats-5",80.0,0.0,"Refresh Women's 'Demi'-05' Round-toe Ballet Flats","Color options: Black, blush, coral, mint, nude, taupe11Style: Flats11Material: Faux leather11Toe shape: Round11Heel height/type: 0.25-inch11Width: Medium11Lining: Fully lined11Sole: Man-made, textured sole11Footbed: Padded11Imported11",null));

//outdoors
list.add(new Item("shoes/outdoors/Men's Merrell Jungle Moc.jpg","shoes","outdoors-1",120.0,0.0,"Men's Merrell Jungle Moc","Abrasion-resistant toe bumper11Air Cushion Heel11Back pull loop11Breathable mesh lining11Compression molded EVA footframe11M-Select FRESH11M-Select GRIP11Realtree Camo®-printed fabric upper11Removable insole11Twin goring11Weight: 1 lb, 8 oz11",null));
list.add(new Item("shoes/outdoors/Men's New Balance MW759.jpg","shoes","outdoors-2",110.0,0.0,"Men's New Balance MW759","Built for the adventurous walker and light hiker who spends plenty of time off the beaten path and needs an incredibly durable shoe, the New Balance MW759 athletic shoe. This men's walking shoe features a suede and mesh upper with full-length ABZORB® cushioning for maximum cushioning and a seamless fabric lining. The C-CAP® compression-molded EVA midsole has a soft ENCAP® EVA core and polyurethane rim for added support and durability. Achieve optimal arch support through the Stability Web®. The Ndurance® rubber outsole provides reliable traction in the New Balance 759 exercise shoe.11",null));
list.add(new Item("shoes/outdoors/Women's Merrell All Out Charge.jpg","shoes","outdoors-3",80.0,15.0,"Women's Merrell All Out Charge","Show the trail who's boss in the slick, sleek Merrell All Out Charge hiking shoe. Featuring the HyperWrap 360 Degree Fit System to lock the foot in place, this vegan-friendly women's trail shoe has a breathable mesh and synthetic upper with a protective, responsive UniFly™ midsole and nylon arch shank for energizing support and reflective hits for low-light visibility. The removable insole features M Select™ FRESH to combat odor atop the responsive M Select™ GRIP outsole, which is equipped with 5mm lugs to bite into the terrain.116mm drop / 20mm cush / 27m stack height11Approx. weight: 8.4 oz. (½ pair)11HyperWrap 360 Degree Fit System11Logo and reflectivity details11M Select™ FRESH11M Select™ GRIP11Mesh and synthetic upper11Molded nylon arch shank11Padded tongue and collar11Removable, cushioned insole11Rubber outsole with 5mm lug depth11UniFly™11Vegan friendly11",null));
list.add(new Item("shoes/outdoors/Women's Under Armour UA Glenrock Low.jpg","shoes","outdoors-4",70.0,0.0,"Women's Under Armour UA Glenrock Low","Antimicrobial foam-cushioned footbed11ArmourVent11HeatGear®11Lightly padded tongue and collar11Mesh textile upper11OrthoLite®\n11Perforations and logo details11Protection plate11Rubber lug outsole11Three-loop, two-eye lace closure11TPU shank11Welded synthetic leather overlays11",null));
list.add(new Item("shoes/outdoors/Women's Vasque Inhaler Low.jpg","shoes","outdoors-5",60.0,0.0,"Women's Vasque Inhaler Low","4mm waterproof leather and 3D structured mesh upper11Approx. weight: 1 lb. 8 oz. / 670 g (pair)11Dual-density EVA footbed11Equalizer Last11Ghillie-style loop and eyelet closure11Logo details11Molded EVA midsole11Padded tongue and collar11Toe and heel ventilation ports11Vibram®11Vibram® Pneumatic with Megagrip Compound outsole11Webbing back pull loop11",null));

//sandals
list.add(new Item("shoes/sandals/Crocs.jpg","shoes","sandals-1",80.0,0.0,"Crocs","Sole Material:CROSLITE11Inner Lining	:CROSLITE11Closing:Slip On11Tip shape:Open11Color:Multi11Upper Material Details:Croslite11",null));
list.add(new Item("shoes/sandals/Dune Harah black Sandals.jpg","shoes","sandals-2",100.0,0.0,"Dune Harah black Sandals","Sole Material:TPR11Inner Lining:Leather11Closing:Buckle11Heel shape:Block11Heel height	Low: 1.5-2.5 Inch11Tip shape:Open11Upper Material Details:Suede Leather11",null));
list.add(new Item("shoes/sandals/Dune Hydro black sandals.jpg","shoes","sandals-2",90.0,0.0,"Dune Hydro black sandals","Sole Material:Resin Sheet11Inner Lining:SYNTHETIC11Closing:Buckle11Heel shape:Stiletto11Heel height:Medium: 2.5-3.5 Inch11Tip shape:Open11Color:Black11Upper Material Details:Suede Leather11",null));
list.add(new Item("shoes/sandals/Get Glamr.jpg","shoes","sandals-4",120.0,0.0,"Get Glamr","Sole Material:Resinsheet11Inner Lining:Synthetic11Closing:Slip On11Heel shape:Kitten11Heel height:Medium: 2.5-3.5 Inch11Color:copper11Upper Material Details:Synthetic11",null));
list.add(new Item("shoes/sandals/Metro Black Sandals.jpg","shoes","sandals-5",140.0,0.0,"Metro Black Sandals","Sole Material:pn11Inner Lining:Synthetic11Closing:Slip On11Heel shape:Kitten11Heel height low:1.5-2.5inch11Color:Black11Upper Material Details:Synthetic11",null));

//slippers
list.add(new Item("shoes/slippers/Adda Brown Men Slippers.jpg","shoes","slippers-1",50.0,0.0,"Adda Brown Men Slippers","OCCASION:Daily11COLOUR FAMILY:Brown11MATERIAL FAMILY:Faux Leather11SOLE FAMILY:Polyurethane (PU)11CLOSING:Buckled",null));
list.add(new Item("shoes/slippers/BNG Red And Black Men Slippers.jpg","shoes","slippers-2",50.0,0.0,"BNG Red And Black Men Slippers","CATEGORY	:Slippers & Flip Flops11OCCASION:Daily11CLOSING	:Slip Ons11MATERIAL FAMILY:Synthetic Leather11SOLE FAMILY:Ethylene Vinyl Acetate (EVA)11TYPE:Slippers11",null));
list.add(new Item("shoes/slippers/Flipside Blue Men Slippers.jpg","shoes","slippers-3",50.0,0.0,"Flipside Blue Men Slippers","CATEGORY	:Slippers & Flip Flops1111COLOUR FAMILY	:Blue11CLOSING:Slip Ons11MATERIAL:Ethylene Vinyl Acetate (EVA)11SOLE:Ethylene Vinyl Acetate (EVA)11",null));
list.add(new Item("shoes/slippers/Lee Cooper Dark Grey And White Men Slippers -LC4552.jpg","shoes","slippers-4",50.0,40.0,"Lee Cooper Dark Grey And White Men Slippers -LC4552","CATEGORY:Slippers & Flip Flops11OCCASION:Daily11COLOUR	:Dark Grey, White11MATERIAL FAMILY:Fabric11SOLE:Ethylene Vinyl Acetate (EVA)11",null));
list.add(new Item("shoes/slippers/Lee Cooper Grey And Red Men Slippers -LC4552.jpg","shoes","slippers-5",50.0,0.0,"Lee Cooper Grey And Red Men Slippers -LC4552","CATEGORY:Slippers & Flip Flops11COLOUR:Grey,Red11CLOSING:Slip Ons11SOLE:Ethylene Vinyl Acetate (EVA)11TYPE	Slippers11",null));
//
//System.out.println(" total size "+list.size()); 
// System.out.println(list);
 
  //outwears
//list.add(new Item("Fashion/outwears/Chic Solid Long-Sleeve Oversized Longline Coat.jpg","Fashion","outerwears-1",25.0,10.0,"Chic Solid Long-Sleeve Oversized Longline Coat","INCH11S:Shoulder:13½,Sleeve:23¼,Length:30,Bust:37¼11M:  Shoulder:14,Sleeve:23¾,Length:30½,Bust:38¾11L:   Shoulder:14¼,Sleeve:24¼,Length:30¾,Bust:40¼\n11:11S:Shoulder:34,Sleeve:59,Length:76,Bust:9411M:  Shoulder:35,Sleeve:60,Length:77,Bust:9811L:Shoulder:36,Sleeve:61,Length:78,Bust:102",null));
//list.add(new Item("Fashion/outwears/Fashion Warm Plaid Open Front Black Woolen Coat.jpg","Fashion","outerwears-2",20.0,10.0,"Fashion Warm Plaid Open Front Black Woolen Coat","INCH11one size:Sleeve:12¼,Length:30,Bust:55¼11one size:Sleeve:32,Length:76,Bust:14011",null));
//list.add(new Item("Fashion/outwears/Floral Graphic Black Bomber Jacket.jpg","Fashion","outerwears-3",35.0,10.0,"Floral Graphic Black Bomber Jacket","INCH11S:   Sleeve:22½,Length:21¾,Bust:35½11M:  Sleeve:23¼,Length:22½,Bust:36¼11L:   Sleeve:24¼,Length:23¼,Bust:37¼\11S:   Sleeve:57,Length:55,Bust:9011M:  Sleeve:59,Length:57,Bust:9211L:   Sleeve:61,Length:59,Bust:9411",null));
//list.add(new Item("Fashion/outwears/Luxe Netted Pattern Jacket.jpg","Fashion","outerwears-4",55.0,10.0,"Luxe Netted Pattern Jacket","INCH11S:   Shoulder:14¼,Sleeve:23,Length:21¾,Bust:37¼11M:  Shoulder:15,Sleeve:23¾,Length:22½,Bust:39½11L:   Shoulder:15¾,Sleeve:24½,Length:23¼,Bust:4111S:   Shoulder:36,Sleeve:58,Length:55,Bust:9611M:  Shoulder:38,Sleeve:60,Length:57,Bust:10011L:   Shoulder:40,Sleeve:62,Length:59,Bust:10411",null));
//list.add(new Item("Fashion/outwears/Stylish Olive Green Faux Fur Collar Coat.jpg","Fashion","outerwears-5",45.0,10.0,"Stylish Olive Green Faux Fur Collar Coat","INCH11S:   Shoulder:14¼,Sleeve:23¾,Length:29¾,Bust:37¼11M:  Shoulder:14¾,Sleeve:24¼,Length:30,Bust:38¾11L:   Shoulder:15,Sleeve:24½,Length:30½,Bust:40¼11S:   Shoulder:36,Sleeve:60,Length:75,Bust:9411M:  Shoulder:37,Sleeve:61,Length:76,Bust:9811L:   Shoulder:38,Sleeve:62,Length:77,Bust:10211",null));
//  
//pants
list.add(new Item("Fashion/pants/Billy London Suit Separates Black Solid Pants.jpg","Fashion","pants-1",50.0,0.0,"Billy London Suit Separates Black Solid Pants","Update your wardrobe with these Suit Separates black pants from Billy London. The pants have a flat front, stylish seam on the pockets for a streamlined look.11Color: Black11Fit: Slim11Solid print11Two (2) back pockets11Zip fly with hook closure11Flat front11Hemmed bottom11",null));
list.add(new Item("Fashion/pants/Brooklyn Xpress Men's Belted Fashion Denim Jean.jpg","Fashion","pants-2", 50.0,0.0,"Brooklyn Xpress Men's Belted Fashion Denim Jean","Printed web belt with dual loop metal closures, riveted pockets, constrast stitch detail11Color: Black11Fit: Slimmer cut straight leg11Pockets: Two (2) front pockets, one (1) coin pocket, two (2) rear patch pockets11Waist details: Constructed waist with belt loops/ button11Type of fly: Zipper with button at waist11Hem situation: Hemmedm11",null));
list.add(new Item("Fashion/pants/Cianni Cellini Men's Navy Wool Gabardine Pants.jpg","Fashion","pants-3",45.0,0.0,"Cianni Cellini Men's Navy Wool Gabardine Pants","Color options: Navy11Fit: Men's 11Pockets: Two (2) front pockets, two (2) button back pockets11Waist details: Belt loops11Type of fly: Zip fly11Hem situation: Unhemmed11",null));
list.add(new Item("Fashion/pants/Cianni Cellini Men's Tan Wool Gabardine Pants.jpg","Fashion","pants-4",50.0,15.0,"Cianni Cellini Men's Tan Wool Gabardine Pants","Color options: Tan11Fit: Men's11Pockets: Two (2) front pockets, two (2)button back pockets11Waist details: Belt loops11Type of fly: Zip fly11Hem situation: Unhemmed11",null));
list.add(new Item("Fashion/pants/Men's Taupe Flat-front Wool Dress Pants.jpg","Fashion","pants-5",45.0,0.0,"Men's Taupe Flat-front Wool Dress Pants","Crafted in soft, virgin wool, these dress pants offer comfort and enduring style to any man's wardrobe.11Classic fit11Taupe color option11Lined to the knee11Front slant pockets11Two back pockets with button closure11Flat front11Unhemmed for customization11",null));

                                
//           Hand bags                      //
//buckets and sags
list.add(new Item("Handbags/Buckets and sacs/As Is Dooney & Bourke Nubuk Leather O-Ring Sac.jpg","Handbags","Buckets and sacs-1",25.0,0.0,"As Is\" Dooney & Bourke Nubuk Leather O-Ring Sac","Nubuk body, adjustable strap with O-ring details, leather logo patch, magnetic closure, four bottom feet11Fully lined interior, back-wall zip and slip pockets, two front-wall slip pockets, key keeper11Measures approximately 12-1/2\"W x 10\"H x 5-1/2\"D with a 12\" to 14\" strap drop; weighs approximately 2 lbs, 9 oz11Body/trim 100% genuine leather; lining 100% cotton11Imported",null));
list.add(new Item("Handbags/Buckets and sacs/Dooney & Bourke Nubuck Leather O-Ring Sac.jpg","Handbags","Buckets and sacs-2",100.0,0.0,"Dooney & Bourke Pebble Leather Zip Sac","Even the most die-hard purse lover has one bag that she gravitates towards again and again. Odds are, this soft, roomy nubuk sac is going to become that bag for you--especially since the O-ring strap adjusts so it doesn't have to go into hibernation when the winter coats come out. From Dooney & Bourke.11Nubuk body, adjustable strap with O-ring details, leather logo patch, magnetic closure, four bottom feet11Fully lined interior, back-wall zip and slip pockets, two front-wall slip pockets, key keeper11Measures approximately 12-1/2\"W x 10\"H x 5-1/2\"D with a 12\" to 14\" strap drop; weighs approximately 2 lbs, 9 oz11Body/trim 100% genuine leather; lining 100% cotton11Imported",null));
list.add(new Item("Handbags/Buckets and sacs/Dooney & Bourke Pebble Leather Zip Sac.jpg","Handbags","Buckets and sacs-3",50.0,0.0,"Dooney & Bourke Nubuck Leather O-Ring Sac","A touch of texture. This Dooney & Bourke sac drops an intricate touch into your casual wardrobe with its rich pebble leather exterior, while a single shoulder strap allows for easy wear. From Dooney & Bourke.11Pebble leather, adjustable strap, two front exterior zip pockets, one back exterior zip pocket, leather logo patch, four bottom feet, top zip closure11Lined interior, two front slip pockets, one back zip, one back slip pocket, and key keeper11Measures approximately 13-3/4\"W x 10\"H x 6\"D with a 21\" to 24\" strap drop; weighs approximately 2 lbs, 9oz11Body/trim 100% leather; lining 100% cotton11Imported",null));
list.add(new Item("Handbags/Buckets and sacs/Dooney & Bourke Pebble Leather Small Sac with Key Fob.jpg","Handbags","Buckets and sacs-4",60.0,0.0,"Dooney & Bourke Pebble Leather Small Sac with Key Fob","Simplify the morning rush. Whether you're running out the door to work or to the store for a few quick errands, this small sac and key fob help you carry the essentials you need. The pebble-textured leather is beautifully contrasted by the trim and handle for signature appeal. From Dooney & Bourke11Pebble leather, key fob, outside zip pocket, shoulder strap with chain detail, zip top closure, burnished hardware11Lined interior, back wall zip pocket and slip pocket, two front-wall slip pockets11Measures 15\"W x 9\"H x 5\"D with a 5\" strap drop; weighs approximately 1 lb, 12 oz11Body/trim 100% leather; lining 100% cotton11Made in China11",null));
list.add(new Item("Handbags/Buckets and sacs/Kelsi Dagger Avery Dip-Dyed Long Shoulder Bucket Bag.jpg","Handbags","Buckets and sacs-5",30.0,0.0,"Kelsi Dagger Avery Dip-Dyed Long Shoulder Bucket Bag","Style: Avery11Dip-dyed, shoulder strap with woven detail, zippered top closure with leather pull, structured bottom11Lined interior, two front-wall slip pockets; one back-wall zippered pocket11Measures approximately 12\"W x 13\"H x 5\"D with an 18\" strap drop; weighs approximately 1 lb11Body/trim 100% leather; lining 100% nylon11Made in China11",null));

//crossbody bags//
list.add(new Item("Handbags/Crossbody bags/Fossil Explorer Straw Cross Body Bag.jpg","Handbags","Crossbody bags-1",20.0,0.0,"Fossil Explorer Straw Cross Body Bag","61.9% Jute/38.1% Polyethylene11Imported11polyester lining11zipper closure1121\" shoulder drop119\" high1111.25\" wide11Signature jacquard lining - 100 polyester interior11Interior features two media pockets and one zipper pocket11Exterior features two zipper pockets11Zip closure1120.25 drop length11Made in China",null));
list.add(new Item("Handbags/Crossbody bags/kate spade new york Cobble Hill Straw Mini Carson Cross Body Bag.jpg","Handbags","Crossbody bags-2",30.0,5.0,"kate spade new york Cobble Hill Straw Mini Carson Cross Body Bag","100% Polyethylene11Imported11polyester lining11zipper closure11Made in China11",null));
list.add(new Item("Handbags/Crossbody bags/Steve Madden Bcharlee Mini Cross Body.jpg","Handbags","Crossbody bags-3",20.0,0.0,"Steve Madden Bcharlee Mini Cross Body","100% Polyurethane11Imported11100% Polyester lining11Twist-Lock closure1122\" shoulder drop114.5\" high116.5\" wide11One interior zip pocket11Made in China11",null));
list.add(new Item("Handbags/Crossbody bags/Ted Baker Domina Distnguish Rose XHTCH Lady Bag.jpg","Handbags","Crossbody bags-4",20.0,0.0,"Ted Baker Domina Distnguish Rose XHTCH Lady Bag","100% Polyvinyl Chloride11Imported11100% Polyester lining11Snap closure1123\" shoulder drop117\" high119.25\" wide11One interior zip and three slip pockets11Made in China11",null));
list.add(new Item("Handbags/Crossbody bags/T-Shirt & Jeans Small Cross Body Bag.jpg","Handbags","Crossbody bags-5",20.0,0.0,"T-Shirt & Jeans Small Cross Body Bag","Polyurethane11Imported11Polyester lining11Zipper closure1126\" shoulder drop117.5\" high1110\" wide11Exterior pocket. One interior zip and two slip pockets11Made in China11",null));

//hobos
list.add(new Item("Handbags/Hobos/Amerileather Cynthia Handbag.jpg","Handbags","Hobos-1",45.0,0.0,"Amerileather Cynthia Handbag","Handbag Material:Leather11Handbag Color:Purple Red11Dimensions:Approx 17 in. L x 17 in. H x 4.25 in.W11Materials:Top Grain Cowhide Leather11Model Number:1805-18",null));
list.add(new Item("Handbags/Hobos/Coach Scout Pebbled Leather Hobo Bag.jpg","Handbags","Hobos-2",45.0,0.0,"Coach Scout Pebbled Leather Hobo Bag","Pebble leather11Color options: Black, nude11Style: Hobo bag11Construction: Leather11Exterior: Pebbled11Entry: Zip-top closure11Hardware: Goldtone11Lining: Logo-jacquard lining11Handles: Single11",null));
list.add(new Item("Handbags/Hobos/Dasein Fashion Hobo Bag.jpg","Handbags","Hobos-3",45.0,0.0,"Dasein Fashion Hobo Bag","Color options: Red, purple11Style: Hobo bag11Construction: Faux leather11Entry: Zip-top closure11Hardware: Silvertone11Lining: Fully lined11Handles: Double rolled11Exterior pockets: One (1) back zip11Interior pockets: One (1) side zip, one (1) cell phone pouch11Country of origin: Imported11Bag dimensions: 9.5 inches high x 17 inches wide x 5 inches deep11Drop: 6 inches11",null));
list.add(new Item("Handbags/Hobos/J. Furmani Women's High Quality Hobo Handbag.jpg","Handbags","Hobos-4",45.0,0.0,"J. Furmani Women's High Quality Hobo Handbag","Metal button accents in front11Color options: Black, brown11Style: Hobo bag11Construction: Vegan leather11Entry: Zip-top closure11Lining: Inside fabric lining11Handles: Double11Interior pockets: One (1) zippered pocket and two (2) media pockets11Bag dimensions: 14 inches high x 8 inches wide x 5 inches deep11Drop: 11 inches11",null));
list.add(new Item("Handbags/Hobos/Patched Corner Hobo Bag.jpg","Handbags","Hobos-5",45.0,0.0,"Patched Corner Hobo Bag","Color options: Blue, Green, Pink, Orange, White, Purple, Silver, Black, Coffee, Blackgreen, Red, Camel, Bronze, Pewter, Coral Red, Light Pink11Style: Hobo bag11Construction: Faux leather11Exterior: Straps connected by carabiner hooks11Entry: Magnetic closure11Hardware: Silvertone hardware11",null));

//Satchels
//list.add(new Item("Handbags/Satchels/Ann Creek 'Moderna' Satchel Bag.jpg","Handbags","Satchels-1",50.0,10.0,))

//System.out.println(" total size "+list.size()); 
// System.out.println(list); 
 return list;
 
}
//public static ArrayList<Item> removeFromTotalElements(String name)
//{
//    ArrayList<Item>   l = new ArrayList<Item>();
//   Object[]   list = l.toArray();
//    System.out.println(list.length);
//    int index=-1;
//    for(int i=0;i<list.length;i++)
//    {
//        if(list[i] instanceof Item)
//        {
//            Item it = (Item) list[i];
//if(it.getSubcategory().equals(name))
//        {
//   index =i;
//        }
//    }}
//   for(int j=index;j<list.length-1;j++)
//   {
//   list[j]=list[j+1];
//   }
//   list[list.length-1]=null;
//   
//        System.out.println(list.length);
//
//    return null;
//}
//    public static void main(String[] args) {
//        System.out.println(Test.Total());
//    }
//list.add(new Item("images/slide2.JPG","Sporting goods","basketball-2",30.0,3.5,"Spalding NBA Neverflat Indoor/Outdoor Basketball","Holds air 10 times longer than traditional basketballs-Provides consistent NBA Game Ball bounce height for at least one year-Redesigned valve with cap eliminates leaks and keeps dirt out-Advanced membrane and NitroFlate air technology virtually eliminates air's ability to escape-Made from high-performance composite leather, for soft, grippy feel",null));
//list.add(new Item("images/slide1.jpg","Sporting goods","basketball-1",50.0,10.0,"Spalding NBA Zi/O Excel Basketball" ,"Indoor/outdoor composite leather basketball-Deep channel design for better dribble control-Foam backing under the full-ball pebbling for precise ball handling-Official NBA size and weight-Intermediate play size 28.5 inches",null));
//list.add(new Item("images/basketball.jpg","Sporting goods","basketball-3",70.0,10.0,"Wilson Evolution Indoor Game Basketball Official" ,"Composite-Imported-Cushion Core Technology features low-density sponge and butyl rubber-High-definition pebble surface improves grip, feel, and performance-3-ply nylon thread winding; air tight butyl rubber valve-Thermal-molded rubber bladder",null));
//list.add(new Item("images/slide3.jpg","Sporting goods","basketball-4",50.0,10.0,"Franklin Sports Night Lightning Basketball" ,"Extremely bright, glow in the dark rubber-Official size and weight, Pro width channels improve feel and performance-Rubber cover provides superior grip and ball handling-Polyester winding provides superior shape retention and bounce, long lasting air retention bladder-Official B7 size is 29.5\" circumference, Recommended age 13+/High school, college and pro",null));
//list.add(new Item(""))
        //         Sporting goods             //
}

